export const TERMS_FULL_CONTENT = [
  {
    id: 'preamble',
    title: 'Preamble',
    content: `These Terms of Service ("Terms," "Agreement") constitute a legally binding contract between Sanothimi Private Limited ("Company," "we," "us," "our"), registered in Nepal with registration number 294812/080/081, and the educational institution ("School," "Client," "you") that subscribes to and uses the SchoolSathi software platform.

    SchoolSathi is a cloud-based school management software (SaaS) designed specifically for schools and educational institutions in Nepal. It provides features including student management, fee collection, examination management, staff HR, transport management, and financial accounting.

    BY CLICKING "I AGREE," SIGNING A SUBSCRIPTION AGREEMENT, OR USING SCHOOLSATHI IN ANY WAY, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT USE SCHOOLSATHI. The authorized representative who registers the School's account confirms they have authority to bind the School to these Terms.`
  },
  {
    id: 'part-1',
    title: 'PART 1 — DEFINITIONS',
    content: `"SchoolSathi" refers to the school management software platform operated by the Company, including the web application, APIs, mobile applications, and all associated services.
    "Account" refers to the School's registered account on SchoolSathi, identified by a unique School Code.
    "Subscription" refers to the paid access plan that allows a School to use SchoolSathi for a defined period.
    "Subscription Fee" refers to the monthly or annual payment made by the School for access to SchoolSathi.
    "School Data" refers to all data entered, uploaded, or generated by the School within SchoolSathi, including student records, staff records, financial records, and exam data.
    "User" refers to any individual — school admin, teacher, accountant, receptionist, or other staff — who accesses SchoolSathi using credentials provided by the School.
    "Super Admin" refers to Company personnel with platform-level administrative access.
    "Downtime" refers to periods when SchoolSathi is inaccessible due to technical issues, maintenance, or other causes.
    "Fiscal Year" means the Nepal fiscal year running from 1st Shrawan to 31st Ashadh.`
  },
  {
    id: 'part-2',
    title: 'PART 2 — ACCOUNT REGISTRATION AND SETUP',
    content: `2.1.1 To use SchoolSathi, a School must complete the registration process, provide accurate institutional information, and agree to these Terms.
    2.1.2 The School must designate at least one School Admin who will be responsible for managing the account.
    2.1.3 Registration info (PAN, address) must be accurate and complete.
    2.2.1 The School is responsible for maintaining the security and confidentiality of all login credentials for all Users under their account.
    2.2.2 The School must immediately notify us at support@sanothimi.com.np if unauthorized access is suspected.
    2.3.1 Upon registration, the Company assigns a unique School Code (e.g., "SDS001") which is permanent.
    2.4.2 The School is responsible for all actions taken by Users under the School's account. User accounts must be deactivated promptly when a staff member leaves.`
  },
  {
    id: 'part-3',
    title: 'PART 3 — SUBSCRIPTION PLANS AND FEES',
    content: `3.1 Basic Plan: Student management, fee collection, basic attendance/exams. (Up to 200 students).
    3.1 Standard Plan: All Basic + full exam module, staff management, payroll, transport. (201–500 students).
    3.1 Premium Plan: All Standard + full accounting (double-entry), IRD compliance, analytics, API access. (501+ students).
    3.1 Custom Enterprise: Negotiated for multi-branch or very large populations.
    3.2.1 Subscriptions are monthly or annual. Annual cycles are billed in advance with a discount.
    3.2.4 Payment via: eSewa, Khalti, bank transfer, cheque, or cash.
    3.3.2 If payment is not received within 15 days of the due date, the account may be placed in read-only mode.
    3.3.3 If payment is not received within 30 days, the account may be suspended.
    3.5.2 Annual subscriptions cancelled within 14 days receive a pro-rated refund minus a 10% fee. No refunds after 14 days.`
  },
  {
    id: 'part-4',
    title: 'PART 4 — LICENSE AND PERMITTED USE',
    content: `4.1 Subject to compliance, the Company grants you a limited, non-exclusive, non-transferable, revocable license to access SchoolSathi solely for managing your school operations.
    4.2.1 You may NOT copy, modify, distribute, sell, or lease any part of SchoolSathi.
    4.2.2 You may NOT reverse engineer, decompile, or attempt to derive the source code.
    4.3.1 SchoolSathi, its design, algorithms, and features, are owned exclusively by Sanothimi Private Limited.
    4.4.1 All School Data entered into the system belongs to you (The School). The Company does not claim ownership of your data.`
  },
  {
    id: 'part-5',
    title: 'PART 5 — ACCEPTABLE USE POLICY',
    content: `5.1 Use must comply with Nepal laws: Education Act, Labour Act, Individual Privacy Act, Electronic Transactions Act.
    5.2.2 You must not knowingly enter false, misleading, or inaccurate information.
    5.3.1 You must handle student data with highest confidentiality and protect it from unauthorized persons.
    5.5.2 You must ensure IRD-compliant invoice numbers are sequential and never skipped.
    5.5.4 Financial records must be verified by your authorized accountant before regulatory submission.`
  },
  {
    id: 'part-6',
    title: 'PART 6 — SERVICE AVAILABILITY AND SUPPORT',
    content: `6.1.1 Target 99% monthly uptime, excluding scheduled maintenance.
    6.2.1 Routine maintenance performed between 11:00 PM and 4:00 AM NPT with 24h notice.
    6.4.1 Support via: email (support@sanothimi.com.np), WhatsApp (+977-985124XXXX), and Phone.
    6.4.2 Support hours: Sunday – Friday, 9:00 AM – 6:00 PM NPT.
    6.4.3 Response targets: Critical (2 hours), High (8 hours), Medium (2 business days).`
  },
  {
    id: 'part-7',
    title: 'PART 7 — DATA HANDLING AND BACKUPS',
    content: `7.2.1 Automated daily backups with 30-day retention.
    7.3.1 Export data anytime using PDF, Excel (XLSX), or JSON functions.
    7.4.1 Upon expiry, account is read-only for 90 days.
    7.4.3 After 90 days of expiry, all School Data is PERMANENTLY deleted and cannot be recovered.`
  },
  {
    id: 'part-8',
    title: 'PART 8 — INTELLECTUAL PROPERTY',
    content: `8.1.1 SchoolSathi source code, design, and architecture are the exclusive IP of Sanothimi Private Limited.
    8.1.3 "SchoolSathi" and "Sanothimi" are registered trademarks.
    8.2.1 Schools retain ownership of all student records, financial data, and institutional branding assets.`
  },
  {
    id: 'part-9',
    title: 'PART 9 — CONFIDENTIALITY',
    content: `9.1 Mutual obligation to keep non-public info confidential.
    9.2 Company ensures all employees and contractors with data access are bound by strict legal confidentiality obligations.
    9.4 Confidentiality doesn't apply to info required by Nepal law or court order.`
  },
  {
    id: 'part-10',
    title: 'PART 10 — WARRANTIES AND DISCLAIMERS',
    content: `10.1 Company warrants substantial performance as documented.
    10.2.1 SchoolSathi is provided "AS IS" beyond express warrants.
    10.2.3 Company does NOT warrant tax computed by system is compliant without accountant verification.`
  },
  {
    id: 'part-11',
    title: 'PART 11 — LIMITATION OF LIABILITY',
    content: `11.1 Total liability shall not exceed subscription fees paid in the 3 months preceding the claim.
    11.2 Company is NOT liable for data loss from User actions, or indirect/consequential damages.
    11.2.7 No liability for unauthorized access due to School's failure to secure credentials.`
  },
  {
    id: 'part-12',
    title: 'PART 12 — FORCE MAJEURE',
    content: `Neither party is liable for delays caused by circumstances beyond control: earthquakes, floods, Nepal govt emergency actions, or nationwide infrastructure failure.`
  },
  {
    id: 'part-13',
    title: 'PART 13 — TERMINATION',
    content: `13.1 Schools may cancel via email at support@sanothimi.com.np.
    13.2.1 Company may terminate if fees are 90 days late or for material breach.
    13.3.3 After 90-day post-termination export period, data deletion is final.`
  },
  {
    id: 'part-14',
    title: 'PART 14 — DISPUTE RESOLUTION',
    content: `14.1 Good faith negotiation required first.
    14.3 Unresolved disputes go to mediation in Kathmandu.
    14.4 Final resolution via binding arbitration in Kathmandu per Arbitration Act, 2055 BS (Nepal).`
  },
  {
    id: 'part-15',
    title: 'PART 15 — GENERAL PROVISIONS',
    content: `These Terms constitute the entire agreement. Amendments require 30 days notice. All legal proceedings shall be conducted under Nepal Law in the courts of Kathmandu.`
  },
  {
    id: 'part-16',
    title: 'PART 16 — CONTACT INFORMATION',
    content: `Sanothimi Private Limited
    Reg No: 294812/080/081 | PAN: 612345678
    Registered Office: Sanothimi, Bhaktapur, Nepal
    Support: support@sanothimi.com.np
    Legal: legal@sanothimi.com.np`
  },
  {
    id: 'schedule-a',
    title: 'SCHEDULE A — DATA PROCESSING AGREEMENT',
    content: `Governs processing for Students, Parents, and Staff. The Company acts as Data Processor. Sub-processors: MongoDB Atlas (Hosting), Cloudinary (Storage), and local SMS providers.`
  },
  {
    id: 'schedule-b',
    title: 'SCHEDULE B — SERVICE LEVEL AGREEMENT',
    content: `Target 99% Uptime. Service credits for uptime < target:
    98.0% – 98.99%: 5% Credit
    95.0% – 97.99%: 10% Credit
    Below 90%: 30% Credit`
  }
];

export const PRIVACY_FULL_CONTENT = [
  {
    id: 'preamble',
    title: 'Preamble',
    content: `SchoolSathi ("we," "our," "us," or "the Company") is a school management software-as-a-service (SaaS) product developed and operated by Sanothimi Private Limited, registered in Nepal. We are committed to protecting the privacy and security of all personal information entrusted to us by educational institutions and their stakeholders.

    This policy is written in compliance with the Individual Privacy Act, 2018 (Nepal) and internationally recognized data protection standards. By using SchoolSathi, you agree to the collection and use of information in accordance with this policy.`
  },
  {
    id: 'part-1',
    title: 'PART 1 — DEFINITIONS',
    content: `"Personal Data" means any information relating to an identified or identifiable natural person.
    "Data Controller" refers to the School, which determines the purposes and means of processing personal data.
    "Data Processor" refers to the Company, which processes data on behalf of the School.
    "Stakeholder" includes school owners, administrators, staff members, students, parents, and legal guardians.`
  },
  {
    id: 'part-2',
    title: 'PART 2 — APPLICABILITY AND SCOPE',
    content: `2.1 This Privacy Policy applies to all individuals whose data is processed through the SchoolSathi platform.
    2.2 It covers institutional accounts, user profiles, student educational records, and staff employment data.
    2.3 It also applies to visitors of our public marketing website (sanothimi.com.np).`
  },
  {
    id: 'part-3',
    title: 'PART 3 — DATA WE COLLECT',
    content: `3.1 Institutional Data: School name, registration details (PAN/VAT), principal contact info, billing addresses, and digital assets like logos.
    3.2 Student Data: Full name, gender, date of birth (BS/AD), blood group, academic performance, attendance, disciplinary records, and health alerts.
    3.3 Parent/Guardian Data: Names, contact numbers, email addresses, and relationship to the student.
    3.4 Staff Data: Personal identity, qualification records, PAN, PF/SSF retirement fund numbers, salary structures, and employment history.
    3.5 Technical Data: IP addresses, browser types, device identifiers, and login audit trails for security monitoring.`
  },
  {
    id: 'part-4',
    title: 'PART 4 — PURPOSES OF PROCESSING',
    content: `4.1 To facilitate school operations: attendance tracking, result management, and portal access.
    4.2 To manage financial records: IRD-compliant fee invoicing and staff payroll processing.
    4.3 To ensure safety: parent notification via SMS for student entry/exit and emergency alerts.
    4.4 To comply with law: maintaining academic records required by the Ministry of Education, Nepal.`
  },
  {
    id: 'part-5',
    title: 'PART 5 — LEGAL BASIS FOR PROCESSING',
    content: `5.1 Contractual Necessity: Processing required to perform the services agreed upon in the Subscription Agreement.
    5.2 Legitimate Interests: Ensuring system security, preventing fraud, and improving infrastructure performance.
    5.3 Legal Obligation: Complying with Nepal's Tax, Labour, and Education regulations.`
  },
  {
    id: 'part-6',
    title: 'PART 6 — DATA ACCESS AND SHARING',
    content: `6.1 Internal Control: Data is strictly isolated. One school's administrators can never see another school's data.
    6.2 Role-Based Access: Teachers can only see data for their assigned classes; accountants can only see financial data.
    6.3 Third-Party Providers: We share data with MongoDB Atlas (Hosting), Cloudinary (Media Storage), and authorized SMS gateways. All are bound by strict Data Processing Agreements.
    6.4 Legal Disclosure: We disclose data to government authorities only if required by a valid legal warrant or court order under Nepal law.`
  },
  {
    id: 'part-7',
    title: 'PART 7 — STORAGE, RETENTION AND DISPOSAL',
    content: `7.1 Global Infrastructure: Data is stored in the Singapore region (MongoDB Atlas) for high performance and disaster recovery.
    7.2 Retention: We retain academic and financial records for 7 years as required by Nepal regulatory framework.
    7.3 Disposal: Upon institutional account termination, data remains in read-only for 90 days for export. After 90 days, all data is permanently and securely erased from our primary and backup systems.`
  },
  {
    id: 'part-8',
    title: 'PART 8 — DATA SECURITY STANDARDS',
    content: `8.1 Encryption at Rest: All database records are encrypted using AES-256.
    8.2 Encryption in Transit: All data moving between the browser and our servers uses TLS 1.3 encryption.
    8.3 Passwords: We use Bcrypt with high salt rounds; we never store plain-text passwords.
    8.4 Backups: Daily automated backups are performed with multi-site redundancy.`
  },
  {
    id: 'part-9',
    title: 'PART 9 — DATA SUBJECT RIGHTS',
    content: `9.1 In accordance with Nepal's Individual Privacy Act, 2018, individuals have the following rights:
    - Right to Access: View the data stored about you.
    - Right to Rectification: Correct inaccurate or incomplete records.
    - Right to Deletion: Request erasure of personal data when no longer needed for educational purposes.
    - Right to Portability: Receive your data in a structured, machine-readable format.`
  },
  {
    id: 'part-10',
    title: 'PART 10 — PROTECTION OF MINORS',
    content: `10.1 We recognize the sensitivity of student data. Schools are responsible for obtaining parental consent before entering student data into SchoolSathi.
    10.2 We do not use student data for marketing, profile-building, or targeted advertising.
    10.3 Student photos are used exclusively for institutional documents like ID Cards and Report Cards.`
  },
  {
    id: 'part-11',
    title: 'PART 11 — COMMUNICATIONS AND NOTIFICATIONS',
    content: `11.1 System Alerts: We send SMS/Email notifications on behalf of schools for fees, attendance, and exam results.
    11.2 Opt-out: Parents may opt-out of optional notifications via their school's administration office.
    11.3 No Marketing: We never send marketing or promotional material to staff, students, or parents.`
  },
  {
    id: 'part-12',
    title: 'PART 12 — COOKIE AND TRACKING POLICY',
    content: `12.1 Necessary Cookies: We use secure session cookies for authentication and CSRF protection.
    12.2 No Ad-Trackers: SchoolSathi does not use third-party advertising trackers or behavioral pixels inside the application.`
  },
  {
    id: 'part-13',
    title: 'PART 13 — INTERNATIONAL DATA TRANSFERS',
    content: `13.1 By subscribing to SchoolSathi, the School acknowledges and consents to the transfer and storage of data in our cloud infrastructure (Singapore).
    13.2 Such locations are chosen to provide security and performance levels that exceed domestic Nepal standards.`
  },
  {
    id: 'part-14',
    title: 'PART 14 — BREACH NOTIFICATION',
    content: `14.1 In the event of a significant data breach, the Company will notify the affected School Admin within 72 hours of discovery.
    14.2 We will provide detailed reports and technical assistance to help schools fulfill their individual notification duties.`
  },
  {
    id: 'part-15',
    title: 'PART 15 — AMENDMENTS TO THIS POLICY',
    content: `15.1 This Privacy Policy may be updated periodically.
    15.2 Active subscribers will be notified of material changes via email at least 30 days before they take effect.`
  },
  {
    id: 'part-16',
    title: 'PART 16 — CONTACT AND GRIEVANCES',
    content: `For any privacy-related inquiries or to exercise your data rights:
    Privacy Officer: privacy@sanothimi.com.np
    Institutional Legal: legal@sanothimi.com.np

    If grievances remain unresolved, individuals may approach the Department of Information Technology (DoIT) or the relevant administrative authority in Nepal.`
  }
];
