export const TERMS_EN = [
  {
    id: 'preamble',
    title: 'Preamble',
    content: `These Terms of Service ("Terms," "Agreement") constitute a legally binding contract between Sanothimi Private Limited ("Company," "we," "us," "our"), registered in Nepal with registration number 294812/080/081, and the educational institution ("School," "Client," "you") that subscribes to and uses the SchoolSathi software platform.

    SchoolSathi is a cloud-based school management software (SaaS) designed specifically for schools and educational institutions in Nepal. It provides features including student management, fee collection, examination management, staff HR, transport management, and financial accounting.

    BY CLICKING "I AGREE," SIGNING A SUBSCRIPTION AGREEMENT, OR USING SCHOOLSATHI IN ANY WAY, YOU CONFIRM THAT YOU HAVE READ, UNDERSTOOD, AND AGREE TO BE BOUND BY THESE TERMS. IF YOU DO NOT AGREE, DO NOT USE SCHOOLSATHI.`
  },
  {
    id: 'part-1',
    title: 'PART 1 — DEFINITIONS',
    content: `"SchoolSathi" refers to the school management software platform operated by the Company, including the web application, APIs, mobile applications, and all associated services.
    "Account" refers to the School's registered account on SchoolSathi, identified by a unique School Code.
    "Subscription" refers to the paid access plan that allows a School to use SchoolSathi for a defined period.
    "Subscription Fee" refers to the monthly or annual payment made by the School for access to SchoolSathi.
    "School Data" refers to all data entered, uploaded, or generated by the School within SchoolSathi, including student records, staff records, financial records, and exam data.`
  },
  {
    id: 'part-2',
    title: 'PART 2 — ACCOUNT REGISTRATION AND SETUP',
    content: `2.1.1 To use SchoolSathi, a School must complete the registration process, provide accurate institutional information, and agree to these Terms.
    2.1.2 The School must designate at least one School Admin who will be responsible for managing the account.
    2.2.1 The School is responsible for maintaining the security and confidentiality of all login credentials for all Users under their account.`
  },
  {
    id: 'part-3',
    title: 'PART 3 — SUBSCRIPTION PLANS AND FEES',
    content: `3.1 Basic Plan: Student management, fee collection, basic attendance/exams. (Up to 200 students).
    3.1 Standard Plan: All Basic + full exam module, staff management, payroll, transport. (201–500 students).
    3.1 Premium Plan: All Standard + full accounting (double-entry), IRD compliance, analytics, API access. (501+ students).
    3.2.1 Subscriptions are monthly or annual. Annual cycles are billed in advance with a discount.`
  },
  {
    id: 'part-4',
    title: 'PART 4 — LICENSE AND PERMITTED USE',
    content: `4.1 Subject to compliance, the Company grants you a limited, non-exclusive, non-transferable, revocable license to access SchoolSathi solely for managing your school operations.
    4.2.1 You may NOT copy, modify, distribute, sell, or lease any part of SchoolSathi.
    4.2.2 You may NOT reverse engineer, decompile, or attempt to derive the source code.`
  },
  {
    id: 'part-5',
    title: 'PART 5 — ACCEPTABLE USE POLICY',
    content: `5.1 Use must comply with Nepal laws: Education Act, Labour Act, Individual Privacy Act, Electronic Transactions Act.
    5.2.2 You must not knowingly enter false, misleading, or inaccurate information.
    5.3.1 You must handle student data with highest confidentiality and protect it from unauthorized persons.`
  },
  {
    id: 'part-6',
    title: 'PART 6 — SERVICE AVAILABILITY AND SUPPORT',
    content: `6.1.1 Target 99% monthly uptime, excluding scheduled maintenance.
    6.2.1 Routine maintenance performed between 11:00 PM and 4:00 AM NPT with 24h notice.
    6.4.1 Support via: email (support@sanothimi.com.np), WhatsApp, and Phone.`
  },
  {
    id: 'part-7',
    title: 'PART 7 — DATA HANDLING AND BACKUPS',
    content: `7.2.1 Automated daily backups with 30-day retention.
    7.3.1 Export data anytime using PDF, Excel (XLSX), or JSON functions.
    7.4.3 After 90 days of expiry, all School Data is PERMANENTLY deleted and cannot be recovered.`
  },
  {
    id: 'part-8',
    title: 'PART 8 — INTELLECTUAL PROPERTY',
    content: `8.1.1 SchoolSathi source code, design, and architecture are the exclusive IP of Sanothimi Private Limited.
    8.2.1 Schools retain ownership of all student records, financial data, and institutional branding assets.`
  },
  {
    id: 'part-9',
    title: 'PART 9 — CONFIDENTIALITY',
    content: `9.1 Mutual obligation to keep non-public info confidential.
    9.2 Company ensures all employees and contractors with data access are bound by strict legal confidentiality obligations.`
  },
  {
    id: 'part-10',
    title: 'PART 10 — WARRANTIES AND DISCLAIMERS',
    content: `10.1 Company warrants substantial performance as documented.
    10.2.1 SchoolSathi is provided "AS IS" beyond express warrants.
    10.2.3 Company does NOT warrant tax computed by system is compliant without accountant verification.`
  },
  {
    id: 'part-11',
    title: 'PART 11 — LIMITATION OF LIABILITY',
    content: `11.1 Total liability shall not exceed subscription fees paid in the 3 months preceding the claim.
    11.2 Company is NOT liable for data loss from User actions, or indirect/consequential damages.`
  },
  {
    id: 'part-12',
    title: 'PART 12 — FORCE MAJEURE',
    content: `Neither party is liable for delays caused by circumstances beyond control: earthquakes, floods, Nepal govt emergency actions, or nationwide infrastructure failure.`
  },
  {
    id: 'part-13',
    title: 'PART 13 — TERMINATION',
    content: `13.1 Schools may cancel via email at support@sanothimi.com.np.
    13.2.1 Company may terminate if fees are 90 days late or for material breach.`
  },
  {
    id: 'part-14',
    title: 'PART 14 — DISPUTE RESOLUTION',
    content: `14.1 Good faith negotiation required first.
    14.4 Final resolution via binding arbitration in Kathmandu per Arbitration Act, 2055 BS (Nepal).`
  },
  {
    id: 'part-15',
    title: 'PART 15 — GENERAL PROVISIONS',
    content: `These Terms constitute the entire agreement. Amendments require 30 days notice. All legal proceedings shall be conducted under Nepal Law.`
  },
  {
    id: 'part-16',
    title: 'PART 16 — CONTACT INFORMATION',
    content: `Sanothimi Private Limited
    Sanothimi, Bhaktapur, Nepal
    Support: support@sanothimi.com.np`
  }
];

export const TERMS_NP = [
  {
    id: 'preamble',
    title: 'प्रस्तावना',
    content: `यी सेवाका सर्तहरू ("सर्तहरू," "सम्झौता") सानोठिमी प्राइभेट लिमिटेड ("कम्पनी," "हामी," "हाम्रो"), नेपालमा दर्ता नम्बर २९४८१२/०८०/०८१ मा दर्ता भएको र स्कूलसाथी सफ्टवेयर प्लेटफर्म प्रयोग गर्ने शैक्षिक संस्था ("विद्यालय," "ग्राहक," "तपाईं") बीचको कानूनी रूपमा बाध्यकारी सम्झौता हो।

    स्कूलसाथी नेपालका विद्यालय र शैक्षिक संस्थाहरूका लागि विशेष रूपमा डिजाइन गरिएको क्लाउड-आधारित विद्यालय व्यवस्थापन सफ्टवेयर (SaaS) हो। यसले विद्यार्थी व्यवस्थापन, शुल्क सङ्कलन, परीक्षा व्यवस्थापन, कर्मचारी प्रशासन, यातायात र वित्तीय लेखा सहितका सुविधाहरू प्रदान गर्दछ।

    "म सहमत छु" मा क्लिक गरेर वा स्कूलसाथी प्रयोग गरेर, तपाईंले यी सर्तहरू पढ्नुभएको, बुझ्नुभएको र बाध्य हुन सहमत हुनुभएको पुष्टि गर्नुहुन्छ।`
  },
  {
    id: 'part-1',
    title: 'भाग १ — परिभाषाहरू',
    content: `"स्कूलसाथी" ले कम्पनीद्वारा सञ्चालित विद्यालय व्यवस्थापन सफ्टवेयर प्लेटफर्मलाई जनाउँछ।
    "खाता" ले स्कूलसाथीमा विद्यालयको दर्ता गरिएको खतालाई जनाउँछ।
    "सदस्यता" ले शुल्क तिरेर निश्चित अवधिका लागि स्कूलसाथी प्रयोग गर्ने अधिकारलाई जनाउँछ।
    "विद्यालय डाटा" ले विद्यालयद्वारा स्कूलसाथीमा प्रविष्ट गरिएको सबै डाटालाई जनाउँछ।`
  },
  {
    id: 'part-2',
    title: 'भाग २ — दर्ता र सेटअप',
    content: `२.१.१ स्कूलसाथी प्रयोग गर्न विद्यालयले दर्ता प्रक्रिया पूरा गर्नुपर्छ र सही संस्थागत जानकारी प्रदान गर्नुपर्छ।
    २.१.२ विद्यालयले खाता व्यवस्थापनका लागि कम्तिमा एक विद्यालय प्रशासक तोक्नुपर्छ।`
  },
  {
    id: 'part-3',
    title: 'भाग ३ — सदस्यता योजना र शुल्क',
    content: `३.१ आधारभूत योजना: विद्यार्थी व्यवस्थापन, शुल्क सङ्कलन। (२०० विद्यार्थीसम्म)।
    ३.१ मानक योजना: परीक्षा मोड्युल, कर्मचारी व्यवस्थापन, पेरोल। (५०० विद्यार्थीसम्म)।
    ३.१ प्रिमियम योजना: पूर्ण लेखा, आन्तरिक राजस्व विभाग अनुरूप। (५०१+ विद्यार्थी)।`
  },
  {
    id: 'part-4',
    title: 'भाग ४ — इजाजतपत्र र प्रयोग',
    content: `४.१ कम्पनीले तपाईंलाई विद्यालय सञ्चालन व्यवस्थापनका लागि मात्र स्कूलसाथी प्रयोग गर्न सीमित इजाजतपत्र प्रदान गर्दछ।
    ४.२ तपाईंले सफ्टवेयरको कुनै पनि भाग प्रतिलिपि गर्न वा परिमार्जन गर्न पाउनुहुने छैन।`
  },
  {
    id: 'part-5',
    title: 'भाग ५ — स्वीकार्य प्रयोग नीति',
    content: `५.१ प्रयोगले नेपालका कानूनहरू: शिक्षा ऐन, व्यक्तिगत गोपनीयता ऐन, विद्युतीय कारोबार ऐनको पालना गर्नुपर्छ।
    ५.३ विद्यार्थीहरूको विवरणलाई पूर्ण रूपमा गोप्य राख्नुपर्छ।`
  },
  {
    id: 'part-6',
    title: 'भाग ६ — सेवा उपलब्धता र समर्थन',
    content: `६.१.१ लक्ष्य ९९% मासिक अपटाइम। मर्मतसम्भार राती ११:०० देखि बिहान ४:०० सम्म गरिनेछ।
    ६.४.१ समर्थनका लागि: support@sanothimi.com.np र व्हाट्सएप।`
  },
  {
    id: 'part-7',
    title: 'भाग ७ — डाटा ह्यान्डलिङ र ब्याकअप',
    content: `७.२.१ ३०-दिनको रिटेन्सनको साथ स्वचालित दैनिक ब्याकअप।
    ७.३.१ कुनै पनि समयमा पीडीएफ वा एक्सेलमा डाटा निर्यात गर्न सकिनेछ।`
  },
  {
    id: 'part-8',
    title: 'भाग ८ — बौद्धिक सम्पत्ति',
    content: `८.१.१ स्कूलसाथीको स्रोत कोड र डिजाइन सानोठिमी प्राइभेट लिमिटेडको विशेष सम्पत्ति हो।
    ८.२.१ विद्यालयले आफ्ना विद्यार्थी रेकर्ड र वित्तीय डाटाको स्वामित्व कायम राख्नेछ।`
  },
  {
    id: 'part-9',
    title: 'भाग ९ — गोपनीयता',
    content: `९.१ गैर-सार्वजनिक जानकारी गोप्य राख्नु दुवै पक्षको आपसी दायित्व हो।
    ९.२ कम्पनीले डाटामा पहुँच भएका सबै कर्मचारीहरू कानूनी गोपनीयता दायित्वहरूद्वारा बाँधिएका छन् भन्ने सुनिश्चित गर्दछ।`
  },
  {
    id: 'part-10',
    title: 'भाग १० — वारेन्टी र अस्वीकरण',
    content: `१०.१ कम्पनीले कागजातमा उल्लेख भए अनुसारको कार्यसम्पादनको वारेन्टी दिन्छ।
    १०.२ कम्पनीले लेखा परीक्षकको प्रमाणीकरण बिना प्रणालीद्वारा गणना गरिएको कर अनुरूप छ भन्ने वारेन्टी दिँदैन।`
  },
  {
    id: 'part-11',
    title: 'भाग ११ — दायित्वको सीमा',
    content: `११.१ कुल दायित्व दाबी गर्नु अघिल्लो ३ महिनामा तिरेको सदस्यता शुल्क भन्दा बढी हुने छैन।
    ११.२ प्रयोगकर्ताका कार्यहरूबाट हुने डाटा नोक्सानीको लागि कम्पनी जिम्मेवार हुने छैन।`
  },
  {
    id: 'part-12',
    title: 'भाग १२ — फोर्स मेज्युर',
    content: `भूकम्प, बाढी वा सरकारी कारबाही जस्ता नियन्त्रण बाहिरका परिस्थितिहरूले गर्दा हुने ढिलाइको लागि कुनै पनि पक्ष जिम्मेवार हुने छैन।`
  },
  {
    id: 'part-13',
    title: 'भाग १३ — समाप्ति',
    content: `१३.१ विद्यालयहरूले इमेल मार्फत सदस्यता रद्द गर्न सक्छन्।
    १३.२ शुल्क तिर्न ९० दिन ढिलो भएमा कम्पनीले सेवा समाप्त गर्न सक्छ।`
  },
  {
    id: 'part-14',
    title: 'भाग १४ — विवाद समाधान',
    content: `१४.१ पहिले सद्भावपूर्ण वार्ता आवश्यक छ।
    १४.४ अन्तिम समाधान काठमाडौंमा मध्यस्थता ऐन, २०५५ बमोजिम गरिनेछ।`
  },
  {
    id: 'part-15',
    title: 'भाग १५ — सामान्य प्रावधानहरू',
    content: `यी सर्तहरूले पूर्ण सम्झौताको गठन गर्दछ। सबै कानूनी कारबाहीहरू नेपाल कानून अन्तर्गत सञ्चालन हुनेछन्।`
  },
  {
    id: 'part-16',
    title: 'भाग १६ — सम्पर्क जानकारी',
    content: `सानोठिमी प्राइभेट लिमिटेड
    सानोठिमी, भक्तपुर, नेपाल
    समर्थन: support@sanothimi.com.np`
  }
];

export const PRIVACY_EN = [
  {
    id: 'preamble',
    title: 'Preamble',
    content: `SchoolSathi ("we," "our," "us," or "the Company") is a school management software-as-a-service (SaaS) product developed and operated by Sanothimi Private Limited. We are committed to protecting the privacy and security of all personal information entrusted to us by educational institutions and their stakeholders.`
  },
  {
    id: 'part-1',
    title: 'PART 1 — DEFINITIONS',
    content: `"Personal Data" means any information relating to an identified or identifiable natural person.
    "Data Controller" refers to the School.
    "Stakeholder" includes school owners, administrators, staff, students, and parents.`
  },
  {
    id: 'part-2',
    title: 'PART 2 — APPLICABILITY',
    content: `2.1 This Privacy Policy applies to all individuals whose data is processed through the SchoolSathi platform.`
  },
  {
    id: 'part-3',
    title: 'PART 3 — DATA WE COLLECT',
    content: `3.1 Institutional Data: School name, registration details (PAN/VAT).
    3.2 Student Data: Full name, gender, birth date, blood group, academic performance.
    3.4 Staff Data: Personal identity, qualification records, salary structures.`
  },
  {
    id: 'part-4',
    title: 'PART 4 — PURPOSES',
    content: `4.1 To facilitate school operations: attendance tracking, result management.
    4.2 To manage financial records: fee invoicing and payroll processing.`
  },
  {
    id: 'part-6',
    title: 'PART 6 — DATA ACCESS',
    content: `6.1 Internal Control: Data is strictly isolated. One school can never see another's data.
    6.2 Role-Based Access: Teachers only see data for their assigned classes.`
  },
  {
    id: 'part-7',
    title: 'PART 7 — STORAGE',
    content: `7.1 Infrastructure: Data is stored in the Singapore region (MongoDB Atlas) for performance.
    7.2 Retention: Records retained for 7 years as required by Nepal regulatory framework.`
  }
];

export const PRIVACY_NP = [
  {
    id: 'preamble',
    title: 'प्रस्तावना',
    content: `स्कूलसाथी ("हामी," "हाम्रो," वा "कम्पनी") नेपालमा दर्ता भएको सानोठिमी प्राइभेट लिमिटेडद्वारा विकसित र सञ्चालित विद्यालय व्यवस्थापन सफ्टवेयर साास (SaaS) उत्पादन हो। हामी शैक्षिक संस्थाहरू र उनीहरूका सरोकारवालाहरूद्वारा हामीमाथि भरोसा गरिएको सबै व्यक्तिगत जानकारीको गोपनीयता र सुरक्षाको रक्षा गर्न प्रतिबद्ध छौं।`
  },
  {
    id: 'part-1',
    title: 'भाग १ — परिभाषाहरू',
    content: `"व्यक्तिगत डाटा" भन्नाले पहिचान गरिएको वा पहिचान गर्न सकिने प्राकृतिक व्यक्तिसँग सम्बन्धित कुनै पनि जानकारीलाई बुझाउँछ।
    "डाटा नियन्त्रक" ले विद्यालयलाई बुझाउँछ।
    "सरोकारवाला" मा विद्यालय मालिक, प्रशासक, कर्मचारी, विद्यार्थी र अभिभावकहरू समावेश छन्।`
  },
  {
    id: 'part-2',
    title: 'भाग २ — लागू हुने क्षेत्र',
    content: `२.१ यो गोपनीयता नीति स्कूलसाथी प्लेटफर्म मार्फत डाटा प्रशोधन गरिने सबै व्यक्तिहरूमा लागू हुन्छ।`
  },
  {
    id: 'part-3',
    title: 'भाग ३ — हामीले सङ्कलन गर्ने डाटा',
    content: `३.१ संस्थागत डाटा: विद्यालयको नाम, दर्ता विवरण (PAN/VAT)।
    ३.२ विद्यार्थी डाटा: पूरा नाम, लिङ्ग, जन्म मिति, रगत समूह, शैक्षिक प्रदर्शन।
    ३.४ कर्मचारी डाटा: व्यक्तिगत पहिचान, योग्यता रेकर्ड, तलब संरचना।`
  },
  {
    id: 'part-4',
    title: 'भाग ४ — प्रशोधनका उद्देश्यहरू',
    content: `४.१ विद्यालय सञ्चालनमा सहजताका लागि: हाजिरी ट्र्याकिङ, नतिजा व्यवस्थापन।
    ४.२ वित्तीय रेकर्डहरू व्यवस्थापन गर्न: शुल्क बीजक र पेरोल प्रशोधन।`
  },
  {
    id: 'part-6',
    title: 'भाग ६ — डाटा पहुँच र साझेदारी',
    content: `६.१ आन्तरिक नियन्त्रण: डाटा कडाईका साथ अलग राखिएको छ। एक विद्यालयले अर्कोको डाटा कहिल्यै देख्न सक्दैन।
    ६.२ भूमिका-आधारित पहुँच: शिक्षकहरूले आफ्नोassigned कक्षाहरूको लागि मात्र डाटा देख्न सक्छन्।`
  },
  {
    id: 'part-7',
    title: 'भाग ७ — भण्डारण र संरक्षण',
    content: `७.१ पूर्वाधार: डाटा कार्यसम्पादनका लागि सिङ्गापुर क्षेत्र (MongoDB Atlas) मा भण्डारण गरिएको छ।
    ७.२ संरक्षण: नेपालको नियामक ढाँचा अनुसार रेकर्डहरू ७ वर्षसम्म सुरक्षित राखिन्छ।`
  }
];

// Compatibility exports
export const TERMS_FULL_CONTENT = TERMS_EN;
export const PRIVACY_FULL_CONTENT = PRIVACY_EN;
