// =========================================================================
// Sanothimi legal content — company-wide documents.
//
// These documents govern "Sanothimi" — the software and technology services
// operated by Chandan Sharma — and cover all current and future SaaS
// products (NUVORA and others), not a single product. Product-specific
// terms, if any, should be published as an addendum layered on top of these
// documents rather than folded into them.
//
// IMPORTANT: Sanothimi is not currently a registered private limited
// company. Do not describe it as "Sanothimi Private Limited" or attach a
// company registration number anywhere in this file until incorporation is
// actually complete and the registration number is confirmed. Update this
// file (and the business identity in this comment) the moment that changes.
//
// NOTE: TERMS_NP and PRIVACY_NP are translated to match the current EN
// content below. DPA, Cookie Policy and Security Policy are shipping
// English-only for now — translate once the wording is stable.
//
// This is draft content, not legal advice. Have a Nepal-qualified lawyer
// review the final wording — especially liability, arbitration, refunds,
// the DPA and cross-border data transfer sections — before relying on it.
// =========================================================================

export const TERMS_EN = [
  {
    id: 'preamble',
    title: '1. Introduction',
    content: `These Terms of Service ("Terms") are a legally binding agreement between you and "Sanothimi," which refers to the software and technology services operated by Chandan Sharma ("Sanothimi," "we," "us," or "our") based in Nepal, and the person or organization accessing or using our websites, software, applications, APIs or services (the "Services," "Customer," "you," or "your").

    By accessing or using a Sanothimi Service, creating an account, subscribing to a Service, signing an order form, or otherwise indicating acceptance, you agree to these Terms. If you are using a Service on behalf of an organization, you represent that you have the authority to bind that organization to these Terms.

    If you do not agree to these Terms, do not access or use our Services.`
  },
  {
    id: 'part-1',
    title: '2. Definitions',
    content: `"Services" means Sanothimi's websites, SaaS products, applications, APIs, and related services, including NUVORA and any other product operated by Sanothimi.
    "SaaS Product" means a specific hosted software product offered by Sanothimi under these Terms.
    "Account" means a Customer's registered account with Sanothimi.
    "Customer" means the organization or individual that registers for or subscribes to a Service.
    "User" means any individual authorized by a Customer to access a Service under the Customer's Account.
    "Customer Data" means any data, content, or information submitted, uploaded, or generated by a Customer or its Users within a Service.
    "Personal Data" means information relating to an identified or identifiable natural person, as further described in our Privacy Policy.
    "Subscription" means the paid or trial plan under which a Customer is authorized to access a Service.
    "Subscription Term" means the period during which a Subscription is active.
    "Documentation" means the user guides, help materials, and technical documentation Sanothimi publishes for a Service.
    "Third-Party Services" means services, integrations, or software provided by a party other than Sanothimi that interoperate with a Service.
    "Order Form" means a document, online purchase flow, or agreement referencing these Terms that specifies the Service, plan, and fees purchased by a Customer.`
  },
  {
    id: 'part-2',
    title: '3. Scope of Services',
    content: `Sanothimi provides websites, cloud software, SaaS applications, mobile applications, APIs, integrations, automation, analytics, and AI-enabled features, together with related support and professional services. Sanothimi's current SaaS portfolio includes NUVORA and may expand to include additional products over time.

    These Terms govern all Services generally. Where a specific SaaS Product has additional product-specific terms, order forms, service agreements, or policies, those product-specific terms apply in addition to these Terms and, to the extent of any conflict regarding that specific product, will control as stated in that product-specific agreement.`
  },
  {
    id: 'part-3',
    title: '4. Eligibility and Authority',
    content: `You must be legally capable of entering into a binding contract to use our Services. If you are registering on behalf of an organization, you represent that you are authorized to accept these Terms on that organization's behalf and to bind it to any applicable Order Form.

    You are responsible for ensuring that your use of the Services, and the use by any Users you authorize, complies with applicable law.`
  },
  {
    id: 'part-4',
    title: '5. Accounts and Registration',
    content: `To use a Service, you must complete registration and provide accurate, current, and complete information about yourself or your organization. You must designate at least one Account administrator responsible for managing Users, permissions, and settings within your Account.

    You are responsible for maintaining the confidentiality and security of all login credentials associated with your Account, for all activity that occurs under your Account, and for promptly notifying us of any unauthorized access or use.`
  },
  {
    id: 'part-5',
    title: '6. SaaS Subscriptions',
    content: `Sanothimi Services are offered under various Subscription models, which may include monthly plans, annual plans, usage-based plans, enterprise plans, and free trials. The specific plan, features, and limits applicable to your Account are described in the applicable Order Form, plan page, or Documentation for the Service you use.

    Sanothimi may introduce, modify, or retire specific plans over time, subject to the notice provisions in these Terms.`
  },
  {
    id: 'part-6',
    title: '7. Plans, Fees and Taxes',
    content: `Subscription fees are billed in advance on a monthly or annual cycle as selected at signup or in the applicable Order Form, unless otherwise agreed. Subscriptions renew automatically at the end of each billing cycle unless cancelled in accordance with these Terms.

    Fees are exclusive of applicable taxes, duties, and government levies unless stated otherwise; you are responsible for any such amounts other than taxes on Sanothimi's net income. Sanothimi may change its fees for future billing cycles with reasonable advance notice.`
  },
  {
    id: 'part-7',
    title: '8. Free Trials',
    content: `Sanothimi may offer free trials of certain Services. Trial duration, feature limitations, and data-handling terms will be disclosed at the time the trial is offered. Unless you cancel before the trial ends, a trial may automatically convert to a paid Subscription where you have provided billing details, or may simply expire and restrict access to the Account where no billing details were provided.

    Sanothimi may terminate or modify a trial at any time without liability.`
  },
  {
    id: 'part-8',
    title: '9. Payment and Billing',
    content: `You authorize Sanothimi or its payment processor to charge your designated payment method for all applicable fees. If a payment fails, we may retry the charge, suspend your Account, or both, after providing reasonable notice.

    Except as required by law or expressly stated in these Terms or an Order Form, fees are non-refundable. Late payments may be subject to suspension as described in Part 21 (Suspension).`
  },
  {
    id: 'part-9',
    title: '10. License and Right to Use',
    content: `Subject to your compliance with these Terms and payment of applicable fees, Sanothimi grants you a limited, non-exclusive, non-transferable, revocable right to access and use the Services during your Subscription Term solely for your internal business or institutional operations.

    This license does not transfer any ownership of the Services to you. You may not copy, modify, distribute, sell, lease, sublicense, reverse engineer, decompile, or attempt to derive the source code of any Service, except to the extent such restriction is prohibited by applicable law.`
  },
  {
    id: 'part-10',
    title: '11. Customer Responsibilities',
    content: `You are responsible for: maintaining the security of your Account and User credentials; using the Services in compliance with applicable law and these Terms; obtaining any permissions or consents required to submit Customer Data to a Service; ensuring the accuracy of information you provide; and ensuring that Customer Data uploaded to a Service is lawful and that you have the right to submit it.`
  },
  {
    id: 'part-11',
    title: '12. Acceptable Use',
    content: `You agree not to use the Services to: violate applicable law, including Nepal's Electronic Transactions Act, Labour Act, and Privacy Act; transmit unlawful, defamatory, or infringing content; attempt to gain unauthorized access to any system or data; interfere with or disrupt the integrity or performance of a Service; introduce malware; or knowingly submit false, misleading, or inaccurate information into a Service.

    Sanothimi may investigate and take appropriate action, including suspension, for any suspected violation of this Part.`
  },
  {
    id: 'part-12',
    title: '13. Customer Content and Data',
    content: `As between the parties, you retain ownership of all Customer Data. You grant Sanothimi a limited right to host, process, transmit, reproduce, and otherwise handle Customer Data only as reasonably necessary to provide, secure, maintain, support, and improve the Services you have subscribed to, subject to applicable law and any applicable Data Processing Agreement.

    Sanothimi does not acquire ownership of Customer Data merely because you use the Services.`
  },
  {
    id: 'part-13',
    title: '14. Third-Party Services and Integrations',
    content: `Services may integrate with or rely on Third-Party Services, including cloud infrastructure providers, payment gateways, communication providers, and APIs. Sanothimi is not responsible for the acts, omissions, availability, or terms of any Third-Party Service. Your use of a Third-Party Service in connection with a Sanothimi Service may be subject to that third party's own terms.`
  },
  {
    id: 'part-14',
    title: '15. Intellectual Property',
    content: `Sanothimi owns and retains all right, title, and interest in and to the Services, including all software, source code, architecture, design, trademarks, logos, and Documentation, and all intellectual property rights therein.

    You retain ownership of Customer Data and any content or materials you create using the Services, subject to the limited rights granted to Sanothimi under Part 13 as reasonably necessary to operate the Services.`
  },
  {
    id: 'part-15',
    title: '16. Confidentiality',
    content: `Each party agrees to protect the other party's non-public, confidential information using at least the same degree of care it uses to protect its own confidential information, and not to disclose it to third parties except as permitted by these Terms, required by law, or necessary to provide or receive the Services. This obligation survives termination of these Terms.`
  },
  {
    id: 'part-16',
    title: '17. Privacy and Data Protection',
    content: `Our collection, use, and handling of Personal Data is described in our Privacy Policy, available at /privacy. Where Sanothimi processes Personal Data on behalf of a business Customer as a processor or service provider, the parties may enter into a Data Processing Agreement, available at /dpa, which forms part of these Terms where executed or otherwise agreed to apply.`
  },
  {
    id: 'part-17',
    title: '18. Security',
    content: `Sanothimi maintains administrative, technical, and organizational safeguards designed to protect the Services and Customer Data, as further described in our Security Policy, available at /security. You are responsible for maintaining reasonable security practices on your end, including credential hygiene and access management within your Account.`
  },
  {
    id: 'part-18',
    title: '19. Service Availability and Maintenance',
    content: `Sanothimi aims to keep the Services available and reliable, but the Services may be temporarily unavailable due to scheduled maintenance, emergency maintenance, third-party outages, or events beyond our reasonable control. Where practical, Sanothimi will provide advance notice of scheduled maintenance likely to cause a service interruption. We do not guarantee uninterrupted or error-free operation of the Services.`
  },
  {
    id: 'part-19',
    title: '20. Support',
    content: `Sanothimi provides standard support for the Services through the channels described in our Support Center, typically including email and, where applicable, phone or chat. Enterprise or premium Customers may be entitled to additional support levels as described in their applicable Order Form.`
  },
  {
    id: 'part-20',
    title: '21. Backups and Data Export',
    content: `Where applicable to a specific Service, Sanothimi performs periodic backups of Customer Data as described in that Service's Documentation or our Security Policy. Sanothimi provides reasonable data export functionality for active Accounts. You are responsible for maintaining your own copies of Customer Data that you consider critical, in addition to relying on Sanothimi's backups.`
  },
  {
    id: 'part-21',
    title: '22. Suspension',
    content: `Sanothimi may suspend your access to a Service, in whole or in part, where reasonably necessary to address: a security threat; suspected illegal activity or fraud; a material breach of these Terms or the Acceptable Use provisions; non-payment of fees; or a risk to the security, availability, or integrity of the Services for other customers. Where practical, Sanothimi will provide notice of a suspension and the reason for it.`
  },
  {
    id: 'part-22',
    title: '23. Termination',
    content: `You may cancel your Subscription at any time in accordance with the cancellation process described for your Service or by contacting support@sanothimi.com. Sanothimi may terminate or decline to renew your access to a Service for material breach of these Terms, non-payment that remains unresolved after reasonable notice, or as otherwise permitted under an applicable Order Form.`
  },
  {
    id: 'part-23',
    title: '24. Effect of Termination',
    content: `Upon termination or expiry of your Subscription: your access to the applicable Service ends; you will have a reasonable period, as described in the applicable Service's Documentation, to export your Customer Data before it is deleted; backups are retained and eventually deleted in accordance with our data retention practices; and any fees owed for the period prior to termination remain due. Sanothimi may retain limited data as required by applicable law or for legitimate record-keeping purposes.`
  },
  {
    id: 'part-24',
    title: '25. Warranties and Disclaimers',
    content: `Sanothimi warrants that it will provide the Services in a manner materially consistent with the applicable Documentation. Except as expressly stated in these Terms or an applicable Order Form, the Services are provided "as is" and "as available," without warranties of any kind, whether express, implied, or statutory, including any implied warranty of merchantability, fitness for a particular purpose, or non-infringement, to the maximum extent permitted by applicable law. Sanothimi does not warrant that the Services will be uninterrupted, error-free, or that outputs (including any tax, accounting, or reporting calculations) are correct without appropriate professional verification.`
  },
  {
    id: 'part-25',
    title: '26. Indemnification',
    content: `You agree to indemnify and hold Sanothimi harmless from third-party claims, damages, and reasonable expenses arising out of: your unlawful use of the Services; Customer Data you submit; your breach of these Terms; or your infringement of a third party's rights, in each case to the extent caused by you or your Users.`
  },
  {
    id: 'part-26',
    title: '27. Limitation of Liability',
    content: `To the maximum extent permitted by applicable law, Sanothimi's total aggregate liability arising out of or related to these Terms or the Services shall not exceed the total Subscription fees paid by you in the three (3) months preceding the event giving rise to the claim. Sanothimi is not liable for indirect, incidental, special, consequential, or punitive damages, or for loss of data resulting from actions taken by you or your Users, except where such limitation is not permitted by applicable law. This Part does not limit liability for gross negligence, willful misconduct, or other liability that cannot be limited under applicable law.`
  },
  {
    id: 'part-27',
    title: '28. Force Majeure',
    content: `Neither party is liable for any delay or failure to perform resulting from causes beyond its reasonable control, including natural disasters (such as earthquakes or floods), war, government action, epidemics, power failures, or major internet or infrastructure failures.`
  },
  {
    id: 'part-28',
    title: '29. Changes to Services',
    content: `Sanothimi may modify, update, or discontinue features of a Service from time to time to improve functionality, security, or performance. Where a change is reasonably likely to have a material adverse effect on a Customer's use of a Service, Sanothimi will provide reasonable advance notice where practical.`
  },
  {
    id: 'part-29',
    title: '30. Changes to Terms',
    content: `Sanothimi may update these Terms from time to time. For material changes, we will provide reasonable advance notice, such as by posting an updated effective date on this page or notifying Account administrators. Continued use of the Services after a change takes effect constitutes acceptance of the updated Terms.`
  },
  {
    id: 'part-30',
    title: '31. Governing Law',
    content: `These Terms are governed by the laws of Nepal, without regard to conflict-of-law principles, except where an applicable Order Form or product-specific agreement with a Customer outside Nepal expressly specifies a different governing law for that relationship.`
  },
  {
    id: 'part-31',
    title: '32. Dispute Resolution',
    content: `The parties will first attempt to resolve any dispute arising out of these Terms through good-faith negotiation. If a dispute cannot be resolved through negotiation within a reasonable period, it will be finally resolved by binding arbitration seated in Kathmandu, Nepal, conducted in accordance with Nepal's Arbitration Act, 2055 (1999), unless the parties agree in writing to a different mechanism or venue for a specific relationship.`
  },
  {
    id: 'part-32',
    title: '33. Notices',
    content: `Legal notices to Sanothimi should be sent to legal@sanothimi.com. Notices to you may be sent to the email address associated with your Account or posted within the applicable Service.`
  },
  {
    id: 'part-33',
    title: '34. General Provisions',
    content: `If any provision of these Terms is found unenforceable, the remaining provisions remain in full force and effect. A party's failure to enforce a provision is not a waiver of that provision. You may not assign these Terms without Sanothimi's prior written consent; Sanothimi may assign these Terms in connection with a merger, acquisition, or sale of assets. These Terms, together with any applicable Order Form and product-specific agreements, constitute the entire agreement between the parties regarding the Services. Provisions that by their nature should survive termination (including Parts 15, 16, 25, 26, and 33) will survive.`
  },
  {
    id: 'part-34',
    title: '35. Contact',
    content: `Sanothimi
    Operated by: Chandan Sharma
    Nepal
    Legal: legal@sanothimi.com
    Support: support@sanothimi.com`
  },
];

export const TERMS_NP = [
  {
    id: 'preamble',
    title: '१. परिचय',
    content: `यी सेवाका सर्तहरू ("सर्तहरू") तपाईं र "सानोठिमी" — चन्दन शर्माद्वारा सञ्चालित सफ्टवेयर तथा प्रविधि सेवा ("सानोठिमी," "हामी," "हाम्रो") — बीचको कानूनी रूपमा बाध्यकारी सम्झौता हो, र हाम्रो वेबसाइट, सफ्टवेयर, एप्लिकेसन, API वा सेवाहरू प्रयोग गर्ने व्यक्ति वा संस्था ("सेवाहरू," "ग्राहक," "तपाईं") बीचको सम्झौता हो।

    कुनै सेवा प्रयोग गरेर, खाता खोलेर, वा सदस्यता लिएर, तपाईंले यी सर्तहरूमा सहमति जनाउनुहुन्छ। संस्थाको तर्फबाट प्रयोग गर्नुहुन्छ भने, तपाईंसँग त्यो संस्थालाई बाँध्ने অधिकার छ ভन्ने তपাঈंले प्रतिनिधित্ব গर्नुहुन्छ।

    यदि तपाईं यी सर्तहरूमा सहमत हुनुहुन्न भने, कृपया हाम्रा सेवाहरू प्रयोग नगर्नुहोस्।`
  },
  {
    id: 'part-1',
    title: '२. परिभाषाहरू',
    content: `"सेवाहरू" ले सानोठिमीका वेबसाइट, साास उत्पादन, एप्लिकेसन, API र सम्बन्धित सेवाहरू (NUVORA सहित) लाई जनाउँछ।
    "खाता" ले सानोठिमीमा ग्राहकको दर्ता गरिएको खातालाई जनाउँछ।
    "ग्राहक" ले सेवाका लागि दर्ता वा सदस्यता लिने संस्था वा व्यक्तिलाई जनाउँछ।
    "प्रयोगकर्ता" ले ग्राहकद्वारा अधिकार प्राप्त व्यक्तिलाई जनाउँछ।
    "ग्राहक डाटा" ले ग्राहक वा प्रयोगकर्ताले सेवामा प्रविष्ट गरेको सबै डाटालाई जनाउँछ।
    "सदस्यता" ले ग्राहकले तिरेको वा ट्रायल योजनालाई जनाउँछ।`
  },
  {
    id: 'part-2',
    title: '३. सेवाको दायरा',
    content: `सानोठिमीले वेबसाइट, क्लाउड सफ्टवेयर, साास एप्लिकेसन, मोबाइल एप्लिकेसन, API, र सम्बन्धित समर्थन सेवाहरू प्रदान गर्दछ। हाम्रो हालको साास पोर्टफोलियोमा NUVORA समावेश छ र भविष्यमा थप उत्पादनहरू थपिन सक्छन्।

    कुनै विशेष उत्पादनका थप उत्पादन-विशेष सर्तहरू भएमा, ती सर्तहरू यी सर्तहरूका अतिरिक्त लागू हुन्छन् र सोही उत्पादनसँग सम्बन्धित द्वन्द्वको हकमा प्राथमिकता पाउँछन्।`
  },
  {
    id: 'part-3',
    title: '४. योग्यता र अधिकार',
    content: `हाम्रो सेवा प्रयोग गर्न तपाईं कानूनी रूपमा बाध्यकारी सम्झौता गर्न सक्षम हुनुपर्छ। संस्थाको तर्फबाट दर्ता गर्दा, तपाईंसँग त्यो संस्थालाई बाँध्ने अधिकार छ भन्ने प्रतिनिधित्व गर्नुहुन्छ।`
  },
  {
    id: 'part-4',
    title: '५. खाता र दर्ता',
    content: `सेवा प्रयोग गर्न तपाईंले सही र पूर्ण जानकारीका साथ दर्ता प्रक्रिया पूरा गर्नुपर्छ र कम्तिमा एक खाता प्रशासक तोक्नुपर्छ। तपाईं आफ्नो खाताको लगइन विवरणको सुरक्षा र गोपनीयता कायम राख्न र अनधिकृत पहुँचको जानकारी तुरुन्त दिन जिम्मेवार हुनुहुन्छ।`
  },
  {
    id: 'part-5',
    title: '६. साास सदस्यता',
    content: `सानोठिमीका सेवाहरू मासिक, वार्षिक, प्रयोग-आधारित, इन्टरप्राइज योजना र निःशुल्क ट्रायल सहित विभिन्न सदस्यता मोडेलमा उपलब्ध छन्। तपाईंको खातामा लागू हुने योजना, सुविधा र सीमाहरू सम्बन्धित अर्डर फर्म वा कागजातमा उल्लेख गरिन्छ।`
  },
  {
    id: 'part-6',
    title: '७. योजना, शुल्क र कर',
    content: `सदस्यता शुल्क साइनअपमा छानिएको मासिक वा वार्षिक चक्रमा अग्रिम रूपमा बिल गरिन्छ र रद्द नगरेसम्म स्वतः नवीकरण हुन्छ। शुल्कमा लागू हुने कर समावेश हुँदैन। भविष्यका बिलिङ चक्रका लागि सानोठिमीले उचित पूर्व सूचना दिएर शुल्क परिवर्तन गर्न सक्छ।`
  },
  {
    id: 'part-7',
    title: '८. निःशुल्क ट्रायल',
    content: `सानोठिमीले केही सेवाहरूको निःशुल्क ट्रायल प्रदान गर्न सक्छ। ट्रायलको अवधि, सुविधा सीमा र डाटा ह्यान्डलिङ सर्तहरू ट्रायल सुरु हुँदा नै जानकारी गराइनेछ। भुक्तानी विवरण दिइएको भए ट्रायल स्वतः सशुल्क सदस्यतामा परिणत हुन सक्छ।`
  },
  {
    id: 'part-8',
    title: '९. भुक्तानी र बिलिङ',
    content: `तपाईंले सानोठिमी वा यसको भुक्तानी प्रोसेसरलाई तोकिएको भुक्तानी माध्यमबाट लागू शुल्क शुल्क लिन अधिकार दिनुहुन्छ। भुक्तानी असफल भएमा उचित सूचना पछि खाता निलम्बन गर्न सकिन्छ। कानून वा यी सर्तहरूमा स्पष्ट उल्लेख बाहेक शुल्क फिर्ता हुँदैन।`
  },
  {
    id: 'part-9',
    title: '१०. इजाजतपत्र र प्रयोगको अधिकार',
    content: `यी सर्तहरूको पालना र लागू शुल्क तिरेको अधीनमा, सानोठिमीले तपाईंलाई सदस्यता अवधिभर आफ्नो संस्थागत कार्यका लागि मात्र सेवा प्रयोग गर्ने सीमित, गैर-विशेष, हस्तान्तरण नहुने अधिकार प्रदान गर्दछ। तपाईंले सफ्टवेयरको स्रोत कोड प्रतिलिपि, परिमार्जन वा रिभर्स इन्जिनियर गर्न पाउनुहुन्न।`
  },
  {
    id: 'part-10',
    title: '११. ग्राहकको जिम्मेवारी',
    content: `तपाईं आफ्नो खाताको सुरक्षा, लागू कानूनको पालना, आवश्यक अनुमति प्राप्ति, दिइएको जानकारीको शुद्धता, र सेवामा अपलोड गरिएको डाटाको वैधताका लागि जिम्मेवार हुनुहुन्छ।`
  },
  {
    id: 'part-11',
    title: '१२. स्वीकार्य प्रयोग',
    content: `तपाईंले सेवालाई नेपालको विद्युतीय कारोबार ऐन, श्रम ऐन वा गोपनीयता ऐन उल्लङ्घन गर्न, गैरकानूनी सामग्री पठाउन, अनधिकृत पहुँच गर्ने प्रयास गर्न, वा गलत जानकारी प्रविष्ट गर्न प्रयोग गर्न पाउनुहुन्न। उल्लङ्घन भएमा सानोठिमीले खाता निलम्बन गर्न सक्छ।`
  },
  {
    id: 'part-12',
    title: '१३. ग्राहक सामग्री र डाटा',
    content: `तपाईंले सबै ग्राहक डाटाको स्वामित्व कायम राख्नुहुन्छ। तपाईंले सानोठिमीलाई सेवा प्रदान, सुरक्षा र सुधारका लागि आवश्यक हदसम्म मात्र डाटा होस्ट, प्रशोधन र सञ्चालन गर्ने सीमित अधिकार दिनुहुन्छ। सेवा प्रयोग गर्दैमा सानोठिमीले डाटाको स्वामित्व प्राप्त गर्दैन।`
  },
  {
    id: 'part-13',
    title: '१४. तेस्रो-पक्ष सेवाहरू',
    content: `सेवाहरू क्लाउड पूर्वाधार, भुक्तानी गेटवे, र अन्य तेस्रो-पक्ष सेवाहरूसँग एकीकृत हुन सक्छन्। सानोठिमी कुनै तेस्रो-पक्ष सेवाको कार्य, उपलब्धता वा सर्तका लागि जिम्मेवार हुँदैन।`
  },
  {
    id: 'part-14',
    title: '१५. बौद्धिक सम्पत्ति',
    content: `सेवाको सफ्टवेयर, स्रोत कोड, डिजाइन, ट्रेडमार्क र कागजातमा सबै अधिकार सानोठिमीको हो। तपाईंले सेवा प्रयोग गरेर सिर्जना गरेको सामग्री र ग्राहक डाटाको स्वामित्व कायम राख्नुहुन्छ।`
  },
  {
    id: 'part-15',
    title: '१६. गोपनीयता (Confidentiality)',
    content: `दुवै पक्षले अर्को पक्षको गैर-सार्वजनिक जानकारीलाई कम्तिमा आफ्नै गोप्य जानकारी जत्तिकै सुरक्षाका साथ राख्नुपर्छ र कानून वा यी सर्तहरूले अनुमति नदिएसम्म तेस्रो पक्षलाई खुलासा गर्नु हुँदैन। यो दायित्व सम्झौता समाप्त भएपछि पनि कायम रहन्छ।`
  },
  {
    id: 'part-16',
    title: '१७. गोपनीयता र डाटा सुरक्षा',
    content: `व्यक्तिगत डाटाको सङ्कलन र प्रयोग सम्बन्धी विवरण हाम्रो गोपनीयता नीति (/privacy) मा उल्लेख गरिएको छ। व्यावसायिक ग्राहकको तर्फबाट प्रशोधन गर्दा, पक्षहरूले डाटा प्रशोधन सम्झौता (/dpa) मा हस्ताक्षर गर्न सक्छन्।`
  },
  {
    id: 'part-17',
    title: '१८. सुरक्षा',
    content: `सानोठिमीले सेवा र ग्राहक डाटाको सुरक्षाका लागि प्रशासनिक, प्राविधिक र संगठनात्मक सुरक्षा उपायहरू कायम राख्दछ, जुन हाम्रो सुरक्षा नीति (/security) मा विस्तृत रूपमा उल्लेख गरिएको छ।`
  },
  {
    id: 'part-18',
    title: '१९. सेवा उपलब्धता र मर्मतसम्भार',
    content: `सानोठिमीले सेवा उपलब्ध र भरपर्दो राख्ने लक्ष्य राख्छ, तर योजनाबद्ध मर्मतसम्भार, आपतकालीन मर्मतसम्भार, वा नियन्त्रण बाहिरका घटनाहरूका कारण सेवा अस्थायी रूपमा अनुपलब्ध हुन सक्छ। सम्भव भएसम्म पूर्व सूचना दिइनेछ।`
  },
  {
    id: 'part-19',
    title: '२०. समर्थन',
    content: `सानोठिमीले इमेल र उपयुक्त भएमा फोन/च्याट मार्फत मानक समर्थन प्रदान गर्दछ। इन्टरप्राइज वा प्रिमियम ग्राहकहरूले सम्बन्धित अर्डर फर्ममा उल्लेख भए बमोजिम थप समर्थन पाउन सक्छन्।`
  },
  {
    id: 'part-20',
    title: '२१. ब्याकअप र डाटा निर्यात',
    content: `लागू हुने सेवाका लागि, सानोठिमीले नियमित ब्याकअप गर्दछ र सक्रिय खाताहरूका लागि डाटा निर्यात सुविधा प्रदान गर्दछ। महत्त्वपूर्ण ठानिएको डाटाको आफ्नै प्रतिलिपि राख्ने जिम्मेवारी तपाईंको हो।`
  },
  {
    id: 'part-21',
    title: '२२. निलम्बन',
    content: `सुरक्षा खतरा, कपटपूर्ण गतिविधि, भौतिक उल्लङ्घन वा भुक्तानी नभएको अवस्थामा सानोठिमीले सेवा निलम्बन गर्न सक्छ। सम्भव भएसम्म निलम्बनको कारणसहित सूचना दिइनेछ।`
  },
  {
    id: 'part-22',
    title: '२३. समाप्ति',
    content: `तपाईंले support@sanothimi.com मार्फत सम्पर्क गरेर जुनसुकै बेला सदस्यता रद्द गर्न सक्नुहुन्छ। भौतिक उल्लङ्घन वा लामो समयसम्म भुक्तानी नभएमा सानोठिमीले सेवा समाप्त गर्न सक्छ।`
  },
  {
    id: 'part-23',
    title: '२४. समाप्तिको प्रभाव',
    content: `सदस्यता समाप्त भएपछि सेवामा पहुँच बन्द हुन्छ। डाटा मेटिनुअघि निर्यात गर्न उचित समय दिइनेछ। ब्याकअपहरू हाम्रो डाटा संरक्षण नीति अनुसार राखिन्छन् र अन्ततः मेटाइन्छन्। समाप्तिअघिको बाँकी शुल्क तिर्नुपर्नेछ।`
  },
  {
    id: 'part-24',
    title: '२५. वारेन्टी र अस्वीकरण',
    content: `सानोठिमीले कागजातमा उल्लेख भए अनुसार सेवा प्रदान गर्ने वारेन्टी दिन्छ। अन्यथा सेवाहरू "जस्ताको तस्तै" प्रदान गरिन्छन्। सानोठिमीले उपयुक्त पेशेवर प्रमाणीकरण बिना कर वा लेखा गणना सही हुने वारेन्टी दिँदैन।`
  },
  {
    id: 'part-25',
    title: '२६. क्षतिपूर्ति',
    content: `तपाईंको गैरकानूनी प्रयोग, तपाईंले प्रविष्ट गरेको डाटा, वा तपाईंको उल्लङ्घनका कारण उत्पन्न तेस्रो-पक्ष दाबीहरूबाट सानोठिमीलाई क्षतिपूर्ति दिन तपाईं सहमत हुनुहुन्छ।`
  },
  {
    id: 'part-26',
    title: '२७. दायित्वको सीमा',
    content: `लागू कानूनले अनुमति दिएको हदसम्म, सानोठिमीको कुल दायित्व दाबी उत्पन्न हुनुअघिका ३ महिनामा तिरेको सदस्यता शुल्कभन्दा बढी हुने छैन। प्रयोगकर्ताका कार्यबाट हुने अप्रत्यक्ष वा परिणामात्मक क्षतिका लागि सानोठिमी जिम्मेवार हुँदैन।`
  },
  {
    id: 'part-27',
    title: '२८. फोर्स मेज्युर',
    content: `भूकम्प, बाढी, युद्ध, सरकारी कारबाही, वा प्रमुख इन्टरनेट/पूर्वाधार विफलता जस्ता नियन्त्रण बाहिरका परिस्थितिहरूले गर्दा हुने ढिलाइ वा विफलताका लागि कुनै पनि पक्ष जिम्मेवार हुने छैन।`
  },
  {
    id: 'part-28',
    title: '२९. सेवामा परिवर्तन',
    content: `सानोठिमीले सुविधा, सुरक्षा वा कार्यसम्पादन सुधार गर्न समय-समयमा सेवामा परिवर्तन गर्न सक्छ। महत्त्वपूर्ण प्रतिकूल असर पर्ने परिवर्तनका लागि सम्भव भएसम्म पूर्व सूचना दिइनेछ।`
  },
  {
    id: 'part-29',
    title: '३०. सर्तहरूमा परिवर्तन',
    content: `सानोठिमीले समय-समयमा यी सर्तहरू अद्यावधिक गर्न सक्छ। महत्त्वपूर्ण परिवर्तनका लागि यस पृष्ठमा अद्यावधिक मिति राखेर वा खाता प्रशासकलाई सूचित गरेर उचित पूर्व सूचना दिइनेछ।`
  },
  {
    id: 'part-30',
    title: '३१. लागू हुने कानून',
    content: `यी सर्तहरू नेपालको कानून अन्तर्गत सञ्चालित हुन्छन्, नेपाल बाहिरका ग्राहकसँगको सम्बन्धमा फरक कानून विशेष रूपमा उल्लेख नगरेसम्म।`
  },
  {
    id: 'part-31',
    title: '३२. विवाद समाधान',
    content: `पक्षहरूले पहिले सद्भावपूर्ण वार्ताबाट विवाद समाधान गर्ने प्रयास गर्नेछन्। समाधान नभएमा, अन्तिम समाधान नेपालको मध्यस्थता ऐन, २०५५ बमोजिम काठमाडौंमा बाध्यकारी मध्यस्थता मार्फत गरिनेछ।`
  },
  {
    id: 'part-32',
    title: '३३. सूचना',
    content: `सानोठिमीलाई कानूनी सूचना legal@sanothimi.com मा पठाउनुपर्छ।`
  },
  {
    id: 'part-33',
    title: '३४. सामान्य प्रावधानहरू',
    content: `यी सर्तहरूको कुनै प्रावधान लागू नभएमा बाँकी प्रावधानहरू यथावत् रहन्छन्। यी सर्तहरू र लागू हुने अर्डर फर्महरूले पक्षहरूबीचको पूर्ण सम्झौता गठन गर्दछ।`
  },
  {
    id: 'part-34',
    title: '३५. सम्पर्क',
    content: `सानोठिमी
    सञ्चालक: चन्दन शर्मा
    नेपाल
    कानूनी: legal@sanothimi.com
    समर्थन: support@sanothimi.com`
  },
];

export const PRIVACY_EN = [
  {
    id: 'preamble',
    title: '1. Who We Are',
    content: `"Sanothimi" refers to the software and technology services operated by Chandan Sharma ("Sanothimi," "we," "us," or "our"), based in Nepal, developing and operating software, SaaS products, websites, applications, APIs, and related technology services, including NUVORA. This Privacy Policy explains how we collect, use, share, and protect personal information across our Services.

    Sanothimi, operated by Chandan Sharma, Nepal.`
  },
  {
    id: 'part-1',
    title: '2. Scope',
    content: `This Privacy Policy applies to website visitors, Customers, Customer employees and Users, prospective customers, support contacts, partners, vendors, and job applicants who interact with Sanothimi. It does not override any product-specific privacy notice or Data Processing Agreement that applies to a particular Service.`
  },
  {
    id: 'part-2',
    title: '3. Controller and Processor Roles',
    content: `For information Sanothimi collects for its own business purposes — such as website analytics, marketing contacts, billing information, and support communications — Sanothimi acts as the controller (or equivalent responsible organization).

    Where a business Customer uses a Sanothimi Service to process personal information on the Customer's behalf (for example, student, staff, or employee data a school or business enters into a Service), Sanothimi acts as a processor or service provider, and the Customer determines the purposes and means of that processing. That relationship may be further defined in a Data Processing Agreement, available at /dpa.`
  },
  {
    id: 'part-3',
    title: '4. Information We Collect',
    content: `Depending on how you interact with us, we may collect: identity and contact information (name, email, phone); account information (login credentials, role); business information (organization name, registration details); billing information (payment details, processed by our payment provider); technical and usage information (IP address, browser, device, pages visited); location information (general, derived from IP address); support communications; and cookie information as described in our Cookie Policy.`
  },
  {
    id: 'part-4',
    title: '5. Customer / SaaS Data',
    content: `Customers may submit their own operational data into a Service — for example, records relating to their staff, students, employees, or clients, depending on the Service. Sanothimi processes this data as instructed by the Customer, as further described in Part 3 (Controller and Processor Roles) and our Data Processing Agreement.`
  },
  {
    id: 'part-5',
    title: '6. Sensitive Information',
    content: `Some Customer Data submitted to a Service may include categories of information treated as sensitive under applicable law. Sanothimi applies additional access controls to such information where technically supported by the Service, and Customers are responsible for ensuring they have a lawful basis to submit such information.`
  },
  {
    id: 'part-6',
    title: '7. How We Use Information',
    content: `We use personal information to: provide and operate the Services; create and manage accounts; authenticate Users; process Subscriptions and payments; provide support; send service-related communications; improve and secure our products; detect and prevent fraud or abuse; analyze usage to improve the Services; comply with legal obligations; and enforce our agreements.`
  },
  {
    id: 'part-7',
    title: '8. Legal Bases',
    content: `Where applicable data protection law requires a legal basis for processing (for example, under GDPR-equivalent frameworks), Sanothimi relies on one or more of the following: performance of a contract, compliance with a legal obligation, our legitimate interests (such as securing and improving the Services), your consent, or protection of vital interests.`
  },
  {
    id: 'part-8',
    title: '9. Consent',
    content: `Where we rely on your consent for a specific processing activity (such as certain marketing communications or non-essential cookies), you may withdraw that consent at any time. Withdrawing consent does not affect the lawfulness of processing carried out before withdrawal.`
  },
  {
    id: 'part-9',
    title: '10. Cookies',
    content: `We use cookies and similar technologies on our websites. Details of the categories of cookies we use, their purposes, and how to manage your preferences are described in our Cookie Policy, available at /cookies.`
  },
  {
    id: 'part-10',
    title: '11. Marketing',
    content: `We may send promotional emails, product announcements, and event communications where permitted. You may opt out of marketing communications at any time using the unsubscribe link in those messages or by contacting us directly. This does not affect transactional or service-related communications necessary to operate your Account.`
  },
  {
    id: 'part-11',
    title: '12. Data Sharing',
    content: `We may share personal information with: hosting and infrastructure providers; payment providers; email and communication providers; analytics and security providers; professional advisers; integrations you authorize; government or law enforcement authorities where legally required; and any party involved in a merger, acquisition, or sale of assets, subject to appropriate confidentiality obligations.`
  },
  {
    id: 'part-12',
    title: '13. Subprocessors',
    content: `Sanothimi engages third-party subprocessors to help provide the Services, such as cloud hosting and database providers. A current list of key subprocessors is available at /subprocessors, or on request to privacy@sanothimi.com.`
  },
  {
    id: 'part-13',
    title: '14. International Transfers',
    content: `Sanothimi uses third-party cloud and infrastructure providers and may process information in jurisdictions outside your own, depending on the Service, Customer configuration, and operational requirements. Where required by applicable law, we use appropriate safeguards for such transfers.`
  },
  {
    id: 'part-14',
    title: '15. Data Storage',
    content: `We do not commit to a single, permanent infrastructure location for all Services. Data is stored with reputable third-party cloud providers selected for performance, reliability, and security, and the specific storage region may vary by Service and may change as our infrastructure evolves.`
  },
  {
    id: 'part-15',
    title: '16. Retention',
    content: `We retain personal information for as long as reasonably necessary for the purposes described in this Policy, including: active account data, for the life of the Account; Customer Data, per the applicable Service's retention settings and Part 21 of our Terms; billing records, as required by tax and accounting law; security logs, for a limited operational period; support records, for a reasonable service-quality period; and backups, which are deleted on a rolling schedule after the underlying data is deleted.`
  },
  {
    id: 'part-16',
    title: '17. Security',
    content: `We maintain administrative, technical, and organizational measures designed to protect personal information, as further described in our Security Policy, available at /security.`
  },
  {
    id: 'part-17',
    title: '18. Data Subject / Privacy Rights',
    content: `Depending on your location and applicable law, you may have rights to: access the personal information we hold about you; request correction of inaccurate information; request deletion; restrict or object to certain processing; request portability of your data; and withdraw consent where processing is based on consent. To exercise these rights, contact privacy@sanothimi.com.`
  },
  {
    id: 'part-18',
    title: '19. Nepal Privacy',
    content: `Sanothimi seeks to comply with applicable Nepalese privacy law, including the Individual Privacy Act, 2075 (2018) and its implementing regulations, as published by the Nepal Law Commission, with respect to personal information we handle as a controller.`
  },
  {
    id: 'part-19',
    title: '20. International Privacy Rights',
    content: `Where applicable law grants you additional rights — for example, under EU/EEA or UK data protection law, or California privacy law — those rights apply to you to the extent that law applies to your relationship with Sanothimi. We do not assume that every regional privacy law applies to every user; applicability depends on your location and the nature of our processing.`
  },
  {
    id: 'part-20',
    title: '21. Children’s Privacy',
    content: `Sanothimi's Services are intended for use by organizations and their authorized adult Users. Where a Customer's use of a Service (for example, an educational institution) involves data relating to children, that Customer is responsible for ensuring it has an appropriate legal basis and any required parental or guardian consent for submitting such data, consistent with our Data Processing Agreement.`
  },
  {
    id: 'part-21',
    title: '22. AI and Automated Processing',
    content: `Certain Services may include AI-assisted features, automated analytics, or automated decision-support tools, which may rely on third-party AI providers. We do not use Customer Data to train third-party foundation models without appropriate safeguards or Customer agreement. Where a Service uses automated processing that produces a decision with a significant effect on an individual, we aim to provide appropriate transparency and, where required by law, a means of human review.`
  },
  {
    id: 'part-22',
    title: '23. Data Breaches',
    content: `We maintain processes to detect, investigate, and respond to security incidents involving personal information. Where a breach is likely to result in a risk to affected individuals, we will notify affected Customers and, where legally required, relevant authorities, without undue delay.`
  },
  {
    id: 'part-23',
    title: '24. Complaints',
    content: `If you have a concern about how we handle personal information, please contact privacy@sanothimi.com first so we can try to resolve it. Where applicable law provides a right to lodge a complaint with a supervisory or regulatory authority, you may also do so.`
  },
  {
    id: 'part-24',
    title: '25. Changes',
    content: `We may update this Privacy Policy from time to time. Material changes will be reflected by an updated "Last Updated" date on this page, and where appropriate, communicated to Account administrators.`
  },
  {
    id: 'part-25',
    title: '26. Contact',
    content: `Sanothimi
    Operated by: Chandan Sharma
    Nepal
    Privacy: privacy@sanothimi.com
    Legal: legal@sanothimi.com`
  },
];

export const PRIVACY_NP = [
  {
    id: 'preamble',
    title: '१. हामी को हौं',
    content: `"सानोठिमी" ले चन्दन शर्माद्वारा सञ्चालित सफ्टवेयर तथा प्रविधि सेवालाई जनाउँछ ("सानोठिमी," "हामी," "हाम्रो"), नेपालमा आधारित, जसले NUVORA लगायत सफ्टवेयर, साास उत्पादन, वेबसाइट, एप्लिकेसन र सम्बन्धित प्राविधिक सेवाहरू विकास र सञ्चालन गर्दछ। यो गोपनीयता नीतिले हाम्रो सेवाहरू मार्फत व्यक्तिगत जानकारी कसरी सङ्कलन, प्रयोग, साझेदारी र सुरक्षित गरिन्छ भन्ने कुरा वर्णन गर्दछ।

    सानोठिमी, सञ्चालक: चन्दन शर्मा, नेपाल।`
  },
  {
    id: 'part-1',
    title: '२. दायरा',
    content: `यो गोपनीयता नीति वेबसाइट अतिथि, ग्राहक, ग्राहकका कर्मचारी र प्रयोगकर्ता, सम्भावित ग्राहक, समर्थन सम्पर्क, साझेदार, विक्रेता र जागिर आवेदकहरूमा लागू हुन्छ।`
  },
  {
    id: 'part-2',
    title: '३. नियन्त्रक र प्रशोधक भूमिका',
    content: `हाम्रो आफ्नै व्यावसायिक उद्देश्यका लागि सङ्कलन गरिने जानकारी (जस्तै वेबसाइट एनालिटिक्स, बिलिङ जानकारी) का लागि सानोठिमी नियन्त्रकको रूपमा कार्य गर्दछ।

    व्यावसायिक ग्राहकले सेवामा आफ्ना कर्मचारी वा विद्यार्थीको डाटा प्रविष्ट गर्दा, सानोठिमीले प्रशोधकको रूपमा कार्य गर्दछ, र ग्राहकले प्रशोधनको उद्देश्य निर्धारण गर्दछ। यो सम्बन्ध डाटा प्रशोधन सम्झौता (/dpa) मा थप परिभाषित गरिन्छ।`
  },
  {
    id: 'part-3',
    title: '४. हामीले सङ्कलन गर्ने जानकारी',
    content: `हामीले पहिचान र सम्पर्क जानकारी, खाता जानकारी, व्यावसायिक जानकारी, बिलिङ जानकारी, प्राविधिक र प्रयोग जानकारी, स्थान जानकारी, समर्थन सञ्चार, र कुकी जानकारी सङ्कलन गर्न सक्छौं।`
  },
  {
    id: 'part-4',
    title: '५. ग्राहक / साास डाटा',
    content: `ग्राहकहरूले आफ्नो कर्मचारी, विद्यार्थी वा ग्राहकसँग सम्बन्धित डाटा सेवामा प्रविष्ट गर्न सक्छन्। सानोठिमीले यो डाटा ग्राहकको निर्देशन अनुसार प्रशोधन गर्दछ।`
  },
  {
    id: 'part-5',
    title: '६. संवेदनशील जानकारी',
    content: `सेवामा प्रविष्ट गरिएको केही ग्राहक डाटा लागू कानून अन्तर्गत संवेदनशील मानिन सक्छ। सानोठिमीले यस्तो जानकारीमा थप पहुँच नियन्त्रण लागू गर्दछ।`
  },
  {
    id: 'part-6',
    title: '७. हामीले जानकारी कसरी प्रयोग गर्छौं',
    content: `हामी व्यक्तिगत जानकारी सेवा प्रदान गर्न, खाता व्यवस्थापन गर्न, भुक्तानी प्रशोधन गर्न, समर्थन दिन, सेवा सुरक्षित र सुधार गर्न, र कानूनी दायित्व पूरा गर्न प्रयोग गर्छौं।`
  },
  {
    id: 'part-7',
    title: '८. कानूनी आधार',
    content: `लागू डाटा सुरक्षा कानूनले कानूनी आधार आवश्यक पारेमा, सानोठिमी सम्झौताको कार्यसम्पादन, कानूनी दायित्व, वैध स्वार्थ, वा तपाईंको सहमतिमा भर पर्दछ।`
  },
  {
    id: 'part-8',
    title: '९. सहमति',
    content: `कुनै विशेष प्रशोधनका लागि तपाईंको सहमतिमा भर पर्दा, तपाईंले जुनसुकै बेला सहमति फिर्ता लिन सक्नुहुन्छ।`
  },
  {
    id: 'part-9',
    title: '१०. कुकीहरू',
    content: `हामी हाम्रो वेबसाइटमा कुकी र समान प्रविधिहरू प्रयोग गर्छौं। विवरणका लागि हाम्रो कुकी नीति (/cookies) हेर्नुहोस्।`
  },
  {
    id: 'part-10',
    title: '११. मार्केटिङ',
    content: `हामी अनुमति भएमा प्रचारात्मक इमेल पठाउन सक्छौं। तपाईं जुनसुकै बेला अनसब्स्क्राइब गर्न सक्नुहुन्छ।`
  },
  {
    id: 'part-11',
    title: '१२. डाटा साझेदारी',
    content: `हामी होस्टिङ प्रदायक, भुक्तानी प्रदायक, इमेल प्रदायक, र कानूनी रूपमा आवश्यक भएमा सरकारी निकायसँग जानकारी साझा गर्न सक्छौं।`
  },
  {
    id: 'part-12',
    title: '१३. सबप्रोसेसरहरू',
    content: `सानोठिमीले सेवा प्रदान गर्न तेस्रो-पक्ष सबप्रोसेसरहरू (जस्तै क्लाउड होस्टिङ) प्रयोग गर्दछ। हालको सूची /subprocessors मा वा privacy@sanothimi.com मा अनुरोध गरेर उपलब्ध छ।`
  },
  {
    id: 'part-13',
    title: '१४. अन्तर्राष्ट्रिय स्थानान्तरण',
    content: `सेवा र ग्राहकको सेटअप अनुसार जानकारी तपाईंको आफ्नै क्षेत्र बाहिर प्रशोधन हुन सक्छ। लागू कानूनले आवश्यक पारेमा हामी उपयुक्त सुरक्षा उपायहरू प्रयोग गर्छौं।`
  },
  {
    id: 'part-14',
    title: '१५. डाटा भण्डारण',
    content: `हामी सबै सेवाका लागि एउटै स्थायी पूर्वाधार स्थानमा प्रतिबद्ध छैनौं। डाटा प्रतिष्ठित तेस्रो-पक्ष क्लाउड प्रदायकहरूमा भण्डारण गरिन्छ, र विशेष भण्डारण क्षेत्र सेवा अनुसार फरक हुन सक्छ।`
  },
  {
    id: 'part-15',
    title: '१६. संरक्षण',
    content: `हामी खाता सक्रिय रहेसम्म खाता डाटा, कर/लेखा कानून अनुसार बिलिङ रेकर्ड, सीमित अवधिका लागि सुरक्षा लग, र मेटाइएपछि क्रमिक रूपमा हटाइने ब्याकअपहरू सुरक्षित राख्छौं।`
  },
  {
    id: 'part-16',
    title: '१७. सुरक्षा',
    content: `हामी व्यक्तिगत जानकारी सुरक्षित गर्न प्रशासनिक, प्राविधिक र संगठनात्मक उपायहरू कायम राख्छौं, जुन हाम्रो सुरक्षा नीति (/security) मा विस्तृत रूपमा उल्लेख गरिएको छ।`
  },
  {
    id: 'part-17',
    title: '१८. गोपनीयता अधिकार',
    content: `लागू कानून अनुसार, तपाईंसँग आफ्नो जानकारीमा पहुँच, सच्याउने, मेटाउने, प्रतिबन्ध लगाउने, र पोर्टेबिलिटीको अधिकार हुन सक्छ। यी अधिकार प्रयोग गर्न privacy@sanothimi.com मा सम्पर्क गर्नुहोस्।`
  },
  {
    id: 'part-18',
    title: '१९. नेपाल गोपनीयता',
    content: `सानोठिमीले नेपाल कानून आयोगद्वारा प्रकाशित व्यक्तिगत गोपनीयता ऐन, २०७५ र सम्बन्धित नियमावली अनुसार व्यक्तिगत जानकारी व्यवस्थापन गर्ने प्रयास गर्दछ।`
  },
  {
    id: 'part-19',
    title: '२०. अन्तर्राष्ट्रिय गोपनीयता अधिकार',
    content: `लागू कानूनले थप अधिकार प्रदान गरेमा (जस्तै EU/EEA वा UK कानून अन्तर्गत), ती अधिकारहरू तपाईंको अवस्था अनुसार लागू हुन्छन्।`
  },
  {
    id: 'part-20',
    title: '२१. बालबालिकाको गोपनीयता',
    content: `सानोठिमीका सेवाहरू संस्था र तिनका अधिकृत वयस्क प्रयोगकर्ताका लागि हुन्। बालबालिकासँग सम्बन्धित डाटा समावेश हुने प्रयोगका लागि, ग्राहक स्वयं उपयुक्त कानूनी आधार र अभिभावकीय सहमति सुनिश्चित गर्न जिम्मेवार हुन्छ।`
  },
  {
    id: 'part-21',
    title: '२२. एआई र स्वचालित प्रशोधन',
    content: `केही सेवाहरूमा एआई-सहायता प्राप्त सुविधा वा स्वचालित एनालिटिक्स समावेश हुन सक्छ। हामी उपयुक्त सुरक्षा उपाय वा ग्राहकको सहमति बिना तेस्रो-पक्ष मोडेल तालिमका लागि ग्राहक डाटा प्रयोग गर्दैनौं।`
  },
  {
    id: 'part-22',
    title: '२३. डाटा उल्लङ्घन',
    content: `व्यक्तिगत जानकारी समावेश भएको सुरक्षा घटना पत्ता लगाउन, अनुसन्धान गर्न र प्रतिक्रिया दिन हामी प्रक्रिया कायम राख्छौं। जोखिम उत्पन्न हुने सम्भावना भएमा हामी प्रभावित ग्राहक र आवश्यक निकायलाई सूचित गर्छौं।`
  },
  {
    id: 'part-23',
    title: '२४. उजुरी',
    content: `हामीले व्यक्तिगत जानकारी कसरी व्यवस्थापन गर्छौं भन्नेबारे कुनै चिन्ता भएमा कृपया privacy@sanothimi.com मा सम्पर्क गर्नुहोस्।`
  },
  {
    id: 'part-24',
    title: '२५. परिवर्तनहरू',
    content: `हामी समय-समयमा यो गोपनीयता नीति अद्यावधिक गर्न सक्छौं। महत्त्वपूर्ण परिवर्तनहरू यस पृष्ठमा अद्यावधिक मिति परिवर्तन गरेर देखाइनेछ।`
  },
  {
    id: 'part-25',
    title: '२६. सम्पर्क',
    content: `सानोठिमी
    सञ्चालक: चन्दन शर्मा
    नेपाल
    गोपनीयता: privacy@sanothimi.com
    कानूनी: legal@sanothimi.com`
  },
];

// =========================================================================
// Data Processing Agreement — English only for now.
// =========================================================================

export const DPA_EN = [
  {
    id: 'preamble',
    title: '1. Parties and Purpose',
    content: `This Data Processing Agreement ("DPA") forms part of the agreement between "Sanothimi" — the software and technology services operated by Chandan Sharma ("Sanothimi," "Processor") — and the customer identified in the applicable Order Form ("Customer," "Controller"), and governs the processing of personal data by Sanothimi on Customer's behalf in connection with the Services.

    Where the main Terms of Service and this DPA conflict with respect to the processing of personal data, this DPA controls to the extent of that conflict.`
  },
  {
    id: 'part-1',
    title: '2. Definitions',
    content: `"Controller," "Processor," "Personal Data," "Processing," and "Data Subject" have the meanings given in applicable data protection law, or if no such definition applies, their generally accepted meaning. "Customer Data" means personal data submitted to a Service by or on behalf of Customer. "Subprocessor" means a third party engaged by Sanothimi to process Customer Data. "Security Incident" means a confirmed breach of security leading to accidental or unlawful destruction, loss, alteration, unauthorized disclosure of, or access to, Customer Data.`
  },
  {
    id: 'part-2',
    title: '3. Roles of the Parties',
    content: `Where Customer determines the purposes and means of processing personal data submitted to a Service, Customer acts as the Controller and Sanothimi acts as the Processor with respect to that Customer Data.`
  },
  {
    id: 'part-3',
    title: '4. Processing Instructions',
    content: `Sanothimi will process Customer Data only in accordance with Customer's documented instructions, as reflected in the applicable Order Form, Service configuration, and this DPA, unless required to do otherwise by applicable law, in which case Sanothimi will inform Customer of that legal requirement before processing, unless prohibited from doing so.`
  },
  {
    id: 'part-4',
    title: '5. Processing Details',
    content: `Subject matter: the provision of the Service purchased by Customer. Duration: the Subscription Term plus any post-termination retention period described in the Terms. Purpose: providing, securing, maintaining, and supporting the Service. Categories of personal data and data subjects: as determined by Customer's use of the Service (which may include Customer's staff, students, employees, or clients). Nature of processing: collection, storage, organization, retrieval, and deletion, as necessary to operate the Service.`
  },
  {
    id: 'part-5',
    title: '6. Confidentiality',
    content: `Sanothimi ensures that personnel authorized to process Customer Data are subject to appropriate confidentiality obligations, whether contractual or statutory.`
  },
  {
    id: 'part-6',
    title: '7. Security Measures',
    content: `Sanothimi implements technical and organizational measures designed to protect Customer Data, as further described in our Security Policy, available at /security, including access controls, encryption in transit, and monitoring appropriate to the nature of the data processed.`
  },
  {
    id: 'part-7',
    title: '8. Subprocessors',
    content: `Customer authorizes Sanothimi's use of the Subprocessors listed at /subprocessors. Sanothimi will provide reasonable notice of the addition of a new Subprocessor where practical, and Customer may object on reasonable data-protection grounds, in which case the parties will work in good faith toward a resolution.`
  },
  {
    id: 'part-8',
    title: '9. Data Subject Requests',
    content: `Where Sanothimi receives a request from a data subject relating to Customer Data, Sanothimi will promptly notify Customer and, taking into account the nature of the processing, provide reasonable assistance to Customer in responding to that request, without responding directly unless required by law.`
  },
  {
    id: 'part-9',
    title: '10. Security Incidents',
    content: `Sanothimi will notify Customer without undue delay after becoming aware of a Security Incident affecting Customer Data, and will provide reasonably available information to help Customer meet its own notification obligations, and take reasonable steps to investigate, contain, and remediate the incident.`
  },
  {
    id: 'part-10',
    title: '11. Government Requests',
    content: `Where legally permitted, Sanothimi will notify Customer of a legally binding request for disclosure of Customer Data from a government or law enforcement authority before disclosing it, unless prohibited from doing so by law.`
  },
  {
    id: 'part-11',
    title: '12. International Transfers',
    content: `Where Sanothimi transfers Customer Data across borders in connection with the Service, it will use appropriate safeguards required by applicable law for such transfers.`
  },
  {
    id: 'part-12',
    title: '13. Deletion and Return',
    content: `Upon termination or expiry of the Subscription, Sanothimi will make Customer Data available for export for the period described in the Terms, after which Customer Data will be deleted from production systems, with backups deleted on a rolling schedule thereafter, subject to any legal retention obligations.`
  },
  {
    id: 'part-13',
    title: '14. Audit and Compliance',
    content: `On reasonable request, and no more than once per year absent a Security Incident or legal requirement, Sanothimi will provide Customer with reasonably available information to demonstrate compliance with this DPA, which may include making available relevant security documentation in lieu of an on-site audit.`
  },
  {
    id: 'part-14',
    title: '15. Liability',
    content: `Each party's liability arising out of this DPA is subject to the limitations of liability set out in the Terms of Service or applicable Order Form.`
  },
  {
    id: 'part-15',
    title: '16. Term',
    content: `This DPA remains in effect for as long as Sanothimi processes Customer Data on Customer's behalf under the Services.`
  },
];

// =========================================================================
// Cookie Policy — English only for now.
// =========================================================================

export const COOKIES_EN = [
  {
    id: 'preamble',
    title: '1. What Are Cookies?',
    content: `Cookies are small text files placed on your device when you visit a website, along with similar technologies such as local storage. This Cookie Policy explains how Sanothimi — the software and technology services operated by Chandan Sharma — uses cookies and similar technologies on its websites and Services, and how you can manage your preferences.`
  },
  {
    id: 'part-1',
    title: '2. Essential Cookies',
    content: `These cookies are necessary for our websites and Services to function, including authentication, session management, security, and basic load balancing. Essential cookies cannot be disabled through our cookie preferences because the Service would not function correctly without them.`
  },
  {
    id: 'part-2',
    title: '3. Functional Cookies',
    content: `These cookies remember preferences such as your selected language, to improve your experience across visits.`
  },
  {
    id: 'part-3',
    title: '4. Analytics Cookies',
    content: `Where used, analytics cookies help us understand how visitors use our website so we can improve it. We only use analytics technologies that we have configured for our own site; we do not maintain a generic list of third parties we do not actually use.`
  },
  {
    id: 'part-4',
    title: '5. Marketing Cookies',
    content: `Where used, marketing cookies may be set to measure the effectiveness of campaigns. As with analytics, we only disclose vendors actually integrated into our website.`
  },
  {
    id: 'part-5',
    title: '6. Third-Party Technologies',
    content: `Some cookies may be set by third-party services embedded in our website, such as a payment provider at checkout. Those third parties are responsible for their own cookies in accordance with their own privacy and cookie notices.`
  },
  {
    id: 'part-6',
    title: '7. Cookie Duration',
    content: `Session cookies are deleted when you close your browser. Persistent cookies remain on your device for a set period, or until you delete them, depending on their purpose.`
  },
  {
    id: 'part-7',
    title: '8. Consent',
    content: `Where required by applicable law, we ask for your consent before setting non-essential cookies, through the cookie banner presented on your first visit. You may change your choice at any time as described below.`
  },
  {
    id: 'part-8',
    title: '9. Managing Cookies',
    content: `You can manage your cookie preferences using the cookie banner on our website, or through your browser settings, which allow you to block or delete cookies. Blocking essential cookies may affect the functionality of our Services.`
  },
  {
    id: 'part-9',
    title: '10. Changes',
    content: `We may update this Cookie Policy from time to time to reflect changes in the technologies we use. Material changes will be reflected by an updated date on this page.`
  },
  {
    id: 'part-10',
    title: '11. Contact',
    content: `Sanothimi
    Operated by: Chandan Sharma
    Nepal
    Privacy: privacy@sanothimi.com`
  },
];

// =========================================================================
// Security Policy — English only for now.
// =========================================================================

export const SECURITY_EN = [
  {
    id: 'preamble',
    title: '1. Security Commitment',
    content: `Security is a fundamental part of how Sanothimi — the software and technology services operated by Chandan Sharma — designs, operates, and maintains its products and services. This Security Policy describes the practices we apply to protect the systems, applications, and customer information entrusted to us. It is intended to build customer trust and is not itself a contractual SLA unless referenced as such in an applicable Order Form.`
  },
  {
    id: 'part-1',
    title: '2. Infrastructure Security',
    content: `Our Services run on reputable third-party cloud infrastructure. We apply network segmentation, firewalls, and separation between environments (such as development, staging, and production) to reduce risk.`
  },
  {
    id: 'part-2',
    title: '3. Encryption',
    content: `We use TLS/HTTPS to encrypt data in transit between your browser or client and our Services. Data at rest is encrypted where supported by the underlying infrastructure provider. We only state encryption practices we actually implement, and update this section as our infrastructure evolves.`
  },
  {
    id: 'part-3',
    title: '4. Identity and Access Management',
    content: `Internal access to production systems and Customer Data is limited on a least-privilege, role-based basis, with periodic review of access grants.`
  },
  {
    id: 'part-4',
    title: '5. Authentication',
    content: `We apply password controls and secure session management for Account access, and support multi-factor authentication where available for a given Service. Credential protection guidance is available in our Documentation.`
  },
  {
    id: 'part-5',
    title: '6. Tenant Isolation',
    content: `For our multi-tenant SaaS Products, Customer environments are logically separated to help prevent unauthorized access to another Customer's information.`
  },
  {
    id: 'part-6',
    title: '7. Logging and Monitoring',
    content: `We maintain security and operational logging designed to help detect and investigate unusual or unauthorized activity affecting our Services.`
  },
  {
    id: 'part-7',
    title: '8. Backup and Recovery',
    content: `We perform periodic backups of Customer Data for Services where applicable, with retention periods described in each Service's Documentation, and maintain recovery procedures intended to restore service in the event of an incident.`
  },
  {
    id: 'part-8',
    title: '9. Vulnerability Management',
    content: `We monitor for known vulnerabilities in our dependencies, apply security patches on a risk-based schedule, and periodically review our systems for security issues.`
  },
  {
    id: 'part-9',
    title: '10. Secure Development',
    content: `Our development practices include code review, dependency and secret management, and separation between development, staging, and production environments.`
  },
  {
    id: 'part-10',
    title: '11. Employee Security',
    content: `Personnel with access to Customer Data are bound by confidentiality obligations, granted access on a need-to-know basis, and have access revoked promptly when no longer required, including upon offboarding.`
  },
  {
    id: 'part-11',
    title: '12. Third-Party Security',
    content: `We rely on established third-party providers for hosting, payment processing, email delivery, and related infrastructure, and select providers with appropriate security practices for the sensitivity of the data they handle.`
  },
  {
    id: 'part-12',
    title: '13. Security Incidents',
    content: `We maintain a process to detect, contain, investigate, and remediate security incidents, and to notify affected Customers in accordance with our Data Processing Agreement and applicable law.`
  },
  {
    id: 'part-13',
    title: '14. Business Continuity',
    content: `We maintain reasonable operational practices intended to support continuity of the Services in the event of a disruption, appropriate to the scale of our current operations.`
  },
  {
    id: 'part-14',
    title: '15. Data Deletion',
    content: `When Customer Data is deleted from production systems (whether by Customer action or upon termination as described in our Terms and DPA), corresponding backups are removed on a rolling schedule thereafter.`
  },
  {
    id: 'part-15',
    title: '16. Customer Responsibilities',
    content: `Security is a shared responsibility. Customers should: use strong, unique credentials; enable multi-factor authentication where available; control which Users have access to their Account and at what permission level; avoid sharing credentials; and report suspected security incidents to us promptly.`
  },
  {
    id: 'part-16',
    title: '17. Compliance and Certifications',
    content: `Certifications: none currently held. We will update this section if and when we obtain formal third-party security certifications, and we do not make certification claims we cannot substantiate.`
  },
  {
    id: 'part-17',
    title: '18. Security Contact',
    content: `To report a suspected security vulnerability or incident, contact:
    security@sanothimi.com`
  },
];

// Compatibility exports
export const TERMS_FULL_CONTENT = TERMS_EN;
export const PRIVACY_FULL_CONTENT = PRIVACY_EN;
